-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv2D_HW_Conv2D_HW_Pipeline_loop_acc_x is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    inputWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    inputHeight : IN STD_LOGIC_VECTOR (31 downto 0);
    y : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln13_1 : IN STD_LOGIC_VECTOR (95 downto 0);
    convWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln13 : IN STD_LOGIC_VECTOR (63 downto 0);
    p_cast10_mid1117 : IN STD_LOGIC_VECTOR (31 downto 0);
    icmp_ln44_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln60 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0);
    filterCoeffs_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_ce0 : OUT STD_LOGIC;
    filterCoeffs_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_1_ce0 : OUT STD_LOGIC;
    filterCoeffs_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_2_ce0 : OUT STD_LOGIC;
    filterCoeffs_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_3_ce0 : OUT STD_LOGIC;
    filterCoeffs_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_4_ce0 : OUT STD_LOGIC;
    filterCoeffs_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_5_ce0 : OUT STD_LOGIC;
    filterCoeffs_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_6_ce0 : OUT STD_LOGIC;
    filterCoeffs_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_7_ce0 : OUT STD_LOGIC;
    filterCoeffs_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_8_ce0 : OUT STD_LOGIC;
    filterCoeffs_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC;
    grp_fu_371_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_371_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_371_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_371_p_ce : OUT STD_LOGIC;
    grp_fu_420_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_420_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_420_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_420_p_ce : OUT STD_LOGIC;
    grp_fu_734_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_734_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_734_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_734_p_ce : OUT STD_LOGIC;
    grp_fu_738_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_738_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_738_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_738_p_ce : OUT STD_LOGIC;
    grp_fu_425_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_425_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_425_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_425_p_ce : OUT STD_LOGIC );
end;


architecture behav of Conv2D_HW_Conv2D_HW_Pipeline_loop_acc_x is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal or_ln58_reg_940 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_reg_940_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state9_io : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal icmp_ln60_reg_900 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln60_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem0_blk_n_AR : STD_LOGIC;
    signal first_iter_1_reg_335 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln60_cast_fu_348_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln60_cast_reg_880 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_cast10_mid1117_cast_fu_352_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast10_mid1117_cast_reg_885 : STD_LOGIC_VECTOR (32 downto 0);
    signal iChannel_reg_890 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln60_fu_395_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln60_reg_895 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln60_reg_900_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln60_reg_900_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_904_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_904_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_904_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_904_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_1_fu_417_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_reg_915_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp4_reg_920 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_40_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_40_reg_925 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp4_mid1_reg_930 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_5_fu_501_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_5_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_5_reg_935_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_5_reg_935_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_reg_940_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_reg_940_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_reg_940_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mid1_fu_532_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid1_reg_944 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln58_2_fu_541_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_2_reg_949_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_fu_557_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln65_reg_954_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_reg_961 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_41_reg_967 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid1111_reg_972 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_589_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid162_reg_978 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln58_fu_649_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln58_reg_983 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln62_mid2_v_reg_988 : STD_LOGIC_VECTOR (61 downto 0);
    signal coeffValue_fu_741_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal coeffValue_reg_1048 : STD_LOGIC_VECTOR (31 downto 0);
    signal pixelValue_reg_1053 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln3_reg_1068 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter6_stage0 : STD_LOGIC;
    signal ap_phi_mux_first_iter_1_phi_fu_340_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln58_2_fu_696_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_fu_680_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_fu_777_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cx_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln62_fu_561_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cy_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln61_fu_549_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten70_fu_128 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln61_1_fu_431_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal iChannel_1_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten161_fu_136 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln60_1_fu_406_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln60_fu_395_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln60_1_fu_417_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln61_1_fu_425_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_42_fu_470_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln62_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_fu_477_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln60_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln58_1_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln61_fu_507_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_44_fu_537_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln60_4_fu_489_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln58_fu_524_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln61_fu_593_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast10_fu_596_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln60_2_fu_608_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln61_1_fu_605_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp5_mid1119_fu_617_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp5_fu_599_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln60_1_fu_613_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast10_mid1_fu_629_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp5_mid1_fu_632_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln60_3_fu_622_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln58_1_fu_638_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln58_fu_645_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln62_mid2_v_v_v_v_v_fu_654_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln58_1_fu_661_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln58_1_fu_665_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_708_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_719_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_730_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_758_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_fu_454_ce : STD_LOGIC;
    signal grp_fu_458_ce : STD_LOGIC;
    signal grp_fu_577_ce : STD_LOGIC;
    signal grp_fu_581_ce : STD_LOGIC;
    signal grp_fu_585_ce : STD_LOGIC;
    signal grp_fu_589_ce : STD_LOGIC;
    signal grp_fu_758_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Conv2D_HW_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Conv2D_HW_mux_32_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Conv2D_HW_mul_32s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component Conv2D_HW_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_2_1_U28 : component Conv2D_HW_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_mid1_reg_944,
        din1 => inputWidth,
        ce => grp_fu_589_ce,
        dout => grp_fu_589_p2);

    mux_32_32_1_1_U29 : component Conv2D_HW_mux_32_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => filterCoeffs_q0,
        din1 => filterCoeffs_1_q0,
        din2 => filterCoeffs_2_q0,
        din3 => trunc_ln65_reg_954_pp0_iter14_reg,
        dout => tmp_fu_708_p5);

    mux_32_32_1_1_U30 : component Conv2D_HW_mux_32_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => filterCoeffs_3_q0,
        din1 => filterCoeffs_4_q0,
        din2 => filterCoeffs_5_q0,
        din3 => trunc_ln65_reg_954_pp0_iter14_reg,
        dout => tmp_1_fu_719_p5);

    mux_32_32_1_1_U31 : component Conv2D_HW_mux_32_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => filterCoeffs_6_q0,
        din1 => filterCoeffs_7_q0,
        din2 => filterCoeffs_8_q0,
        din3 => trunc_ln65_reg_954_pp0_iter14_reg,
        dout => tmp_2_fu_730_p5);

    mux_32_32_1_1_U32 : component Conv2D_HW_mux_32_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_fu_708_p5,
        din1 => tmp_1_fu_719_p5,
        din2 => tmp_2_fu_730_p5,
        din3 => select_ln58_2_reg_949_pp0_iter14_reg,
        dout => coeffValue_fu_741_p5);

    mul_32s_32s_52_2_1_U33 : component Conv2D_HW_mul_32s_32s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => pixelValue_reg_1053,
        din1 => coeffValue_reg_1048,
        ce => grp_fu_758_ce,
        dout => grp_fu_758_p2);

    flow_control_loop_pipe_sequential_init_U : component Conv2D_HW_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter17_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter6_stage0)) then 
                    ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_fu_116 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (icmp_ln60_reg_900_pp0_iter17_reg = ap_const_lv1_0))) then 
                    acc_fu_116 <= acc_1_fu_777_p2;
                end if;
            end if; 
        end if;
    end process;

    cx_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    cx_fu_120 <= ap_const_lv32_0;
                elsif (((icmp_ln60_reg_900_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    cx_fu_120 <= add_ln62_fu_561_p2;
                end if;
            end if; 
        end if;
    end process;

    cy_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    cy_fu_124 <= ap_const_lv32_0;
                elsif (((icmp_ln60_reg_900_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    cy_fu_124 <= select_ln61_fu_549_p3;
                end if;
            end if; 
        end if;
    end process;

    first_iter_1_reg_335_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_reg_900_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_1_reg_335 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_1_reg_335 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    iChannel_1_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    iChannel_1_fu_132 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln60_fu_401_p2 = ap_const_lv1_0))) then 
                    iChannel_1_fu_132 <= select_ln60_1_fu_417_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten161_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten161_fu_136 <= ap_const_lv96_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln60_fu_401_p2 = ap_const_lv1_0))) then 
                    indvar_flatten161_fu_136 <= add_ln60_1_fu_406_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten70_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten70_fu_128 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln60_fu_401_p2 = ap_const_lv1_0))) then 
                    indvar_flatten70_fu_128 <= select_ln61_1_fu_431_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_reg_900_pp0_iter5_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln58_reg_983 <= add_ln58_fu_649_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln60_reg_895 <= add_ln60_fu_395_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                iChannel_reg_890 <= iChannel_1_fu_132;
                icmp_ln60_reg_900 <= icmp_ln60_fu_401_p2;
                    p_cast10_mid1117_cast_reg_885(31 downto 0) <= p_cast10_mid1117_cast_fu_352_p1(31 downto 0);
                    zext_ln60_cast_reg_880(31 downto 0) <= zext_ln60_cast_fu_348_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                empty_reg_961 <= grp_fu_734_p_dout0;
                icmp_ln60_reg_900_pp0_iter10_reg <= icmp_ln60_reg_900_pp0_iter9_reg;
                icmp_ln60_reg_900_pp0_iter11_reg <= icmp_ln60_reg_900_pp0_iter10_reg;
                icmp_ln60_reg_900_pp0_iter12_reg <= icmp_ln60_reg_900_pp0_iter11_reg;
                icmp_ln60_reg_900_pp0_iter13_reg <= icmp_ln60_reg_900_pp0_iter12_reg;
                icmp_ln60_reg_900_pp0_iter14_reg <= icmp_ln60_reg_900_pp0_iter13_reg;
                icmp_ln60_reg_900_pp0_iter15_reg <= icmp_ln60_reg_900_pp0_iter14_reg;
                icmp_ln60_reg_900_pp0_iter16_reg <= icmp_ln60_reg_900_pp0_iter15_reg;
                icmp_ln60_reg_900_pp0_iter17_reg <= icmp_ln60_reg_900_pp0_iter16_reg;
                icmp_ln60_reg_900_pp0_iter2_reg <= icmp_ln60_reg_900;
                icmp_ln60_reg_900_pp0_iter3_reg <= icmp_ln60_reg_900_pp0_iter2_reg;
                icmp_ln60_reg_900_pp0_iter4_reg <= icmp_ln60_reg_900_pp0_iter3_reg;
                icmp_ln60_reg_900_pp0_iter5_reg <= icmp_ln60_reg_900_pp0_iter4_reg;
                icmp_ln60_reg_900_pp0_iter6_reg <= icmp_ln60_reg_900_pp0_iter5_reg;
                icmp_ln60_reg_900_pp0_iter7_reg <= icmp_ln60_reg_900_pp0_iter6_reg;
                icmp_ln60_reg_900_pp0_iter8_reg <= icmp_ln60_reg_900_pp0_iter7_reg;
                icmp_ln60_reg_900_pp0_iter9_reg <= icmp_ln60_reg_900_pp0_iter8_reg;
                icmp_ln61_reg_904_pp0_iter2_reg <= icmp_ln61_reg_904;
                icmp_ln61_reg_904_pp0_iter3_reg <= icmp_ln61_reg_904_pp0_iter2_reg;
                icmp_ln61_reg_904_pp0_iter4_reg <= icmp_ln61_reg_904_pp0_iter3_reg;
                icmp_ln61_reg_904_pp0_iter5_reg <= icmp_ln61_reg_904_pp0_iter4_reg;
                or_ln58_reg_940_pp0_iter4_reg <= or_ln58_reg_940;
                or_ln58_reg_940_pp0_iter5_reg <= or_ln58_reg_940_pp0_iter4_reg;
                or_ln58_reg_940_pp0_iter6_reg <= or_ln58_reg_940_pp0_iter5_reg;
                or_ln58_reg_940_pp0_iter7_reg <= or_ln58_reg_940_pp0_iter6_reg;
                select_ln58_2_reg_949_pp0_iter10_reg <= select_ln58_2_reg_949_pp0_iter9_reg;
                select_ln58_2_reg_949_pp0_iter11_reg <= select_ln58_2_reg_949_pp0_iter10_reg;
                select_ln58_2_reg_949_pp0_iter12_reg <= select_ln58_2_reg_949_pp0_iter11_reg;
                select_ln58_2_reg_949_pp0_iter13_reg <= select_ln58_2_reg_949_pp0_iter12_reg;
                select_ln58_2_reg_949_pp0_iter14_reg <= select_ln58_2_reg_949_pp0_iter13_reg;
                select_ln58_2_reg_949_pp0_iter4_reg <= select_ln58_2_reg_949;
                select_ln58_2_reg_949_pp0_iter5_reg <= select_ln58_2_reg_949_pp0_iter4_reg;
                select_ln58_2_reg_949_pp0_iter6_reg <= select_ln58_2_reg_949_pp0_iter5_reg;
                select_ln58_2_reg_949_pp0_iter7_reg <= select_ln58_2_reg_949_pp0_iter6_reg;
                select_ln58_2_reg_949_pp0_iter8_reg <= select_ln58_2_reg_949_pp0_iter7_reg;
                select_ln58_2_reg_949_pp0_iter9_reg <= select_ln58_2_reg_949_pp0_iter8_reg;
                select_ln60_1_reg_915_pp0_iter10_reg <= select_ln60_1_reg_915_pp0_iter9_reg;
                select_ln60_1_reg_915_pp0_iter11_reg <= select_ln60_1_reg_915_pp0_iter10_reg;
                select_ln60_1_reg_915_pp0_iter12_reg <= select_ln60_1_reg_915_pp0_iter11_reg;
                select_ln60_1_reg_915_pp0_iter13_reg <= select_ln60_1_reg_915_pp0_iter12_reg;
                select_ln60_1_reg_915_pp0_iter2_reg <= select_ln60_1_reg_915;
                select_ln60_1_reg_915_pp0_iter3_reg <= select_ln60_1_reg_915_pp0_iter2_reg;
                select_ln60_1_reg_915_pp0_iter4_reg <= select_ln60_1_reg_915_pp0_iter3_reg;
                select_ln60_1_reg_915_pp0_iter5_reg <= select_ln60_1_reg_915_pp0_iter4_reg;
                select_ln60_1_reg_915_pp0_iter6_reg <= select_ln60_1_reg_915_pp0_iter5_reg;
                select_ln60_1_reg_915_pp0_iter7_reg <= select_ln60_1_reg_915_pp0_iter6_reg;
                select_ln60_1_reg_915_pp0_iter8_reg <= select_ln60_1_reg_915_pp0_iter7_reg;
                select_ln60_1_reg_915_pp0_iter9_reg <= select_ln60_1_reg_915_pp0_iter8_reg;
                select_ln60_5_reg_935_pp0_iter4_reg <= select_ln60_5_reg_935;
                select_ln60_5_reg_935_pp0_iter5_reg <= select_ln60_5_reg_935_pp0_iter4_reg;
                sext_ln62_mid2_v_reg_988 <= add_ln58_1_fu_665_p2(63 downto 2);
                tmp4_reg_920 <= grp_fu_371_p_dout0;
                trunc_ln65_reg_954_pp0_iter10_reg <= trunc_ln65_reg_954_pp0_iter9_reg;
                trunc_ln65_reg_954_pp0_iter11_reg <= trunc_ln65_reg_954_pp0_iter10_reg;
                trunc_ln65_reg_954_pp0_iter12_reg <= trunc_ln65_reg_954_pp0_iter11_reg;
                trunc_ln65_reg_954_pp0_iter13_reg <= trunc_ln65_reg_954_pp0_iter12_reg;
                trunc_ln65_reg_954_pp0_iter14_reg <= trunc_ln65_reg_954_pp0_iter13_reg;
                trunc_ln65_reg_954_pp0_iter4_reg <= trunc_ln65_reg_954;
                trunc_ln65_reg_954_pp0_iter5_reg <= trunc_ln65_reg_954_pp0_iter4_reg;
                trunc_ln65_reg_954_pp0_iter6_reg <= trunc_ln65_reg_954_pp0_iter5_reg;
                trunc_ln65_reg_954_pp0_iter7_reg <= trunc_ln65_reg_954_pp0_iter6_reg;
                trunc_ln65_reg_954_pp0_iter8_reg <= trunc_ln65_reg_954_pp0_iter7_reg;
                trunc_ln65_reg_954_pp0_iter9_reg <= trunc_ln65_reg_954_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0))) then
                coeffValue_reg_1048 <= coeffValue_fu_741_p5;
                pixelValue_reg_1053 <= m_axi_gmem0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_reg_904_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_40_reg_925 <= empty_40_fu_465_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln60_5_reg_935_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln61_reg_904_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_41_reg_967 <= grp_fu_738_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln60_fu_401_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln61_reg_904 <= icmp_ln61_fu_412_p2;
                select_ln60_1_reg_915 <= select_ln60_1_fu_417_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_reg_900_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                or_ln58_reg_940 <= or_ln58_fu_513_p2;
                p_mid1_reg_944 <= p_mid1_fu_532_p2;
                select_ln58_2_reg_949 <= select_ln58_2_fu_541_p3;
                select_ln60_5_reg_935 <= select_ln60_5_fu_501_p3;
                tmp4_mid1_reg_930 <= grp_fu_420_p_dout0;
                trunc_ln65_reg_954 <= trunc_ln65_fu_557_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_reg_900_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_mid1111_reg_972 <= grp_fu_425_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln60_5_reg_935_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln60_reg_900_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_mid162_reg_978 <= grp_fu_589_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_reg_900_pp0_iter16_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                trunc_ln3_reg_1068 <= grp_fu_758_p2(51 downto 20);
            end if;
        end if;
    end process;
    zext_ln60_cast_reg_880(33 downto 32) <= "00";
    p_cast10_mid1117_cast_reg_885(32) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_1_fu_777_p2 <= std_logic_vector(unsigned(trunc_ln3_reg_1068) + unsigned(acc_fu_116));
    acc_out <= acc_fu_116;

    acc_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln60_reg_900_pp0_iter16_reg)
    begin
        if (((icmp_ln60_reg_900_pp0_iter16_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln58_1_fu_665_p2 <= std_logic_vector(unsigned(zext_ln58_1_fu_661_p1) + unsigned(input_r));
    add_ln58_fu_649_p2 <= std_logic_vector(unsigned(zext_ln58_fu_645_p1) + unsigned(zext_ln60_cast_reg_880));
    add_ln60_1_fu_406_p2 <= std_logic_vector(unsigned(indvar_flatten161_fu_136) + unsigned(ap_const_lv96_1));
    add_ln60_fu_395_p0 <= iChannel_1_fu_132;
    add_ln60_fu_395_p2 <= std_logic_vector(signed(add_ln60_fu_395_p0) + signed(ap_const_lv32_1));
    add_ln61_1_fu_425_p2 <= std_logic_vector(unsigned(indvar_flatten70_fu_128) + unsigned(ap_const_lv64_1));
    add_ln61_fu_507_p2 <= std_logic_vector(unsigned(select_ln60_fu_477_p3) + unsigned(ap_const_lv32_1));
    add_ln62_fu_561_p2 <= std_logic_vector(unsigned(select_ln58_fu_524_p3) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter15, m_axi_gmem0_RVALID, icmp_ln60_reg_900_pp0_iter14_reg)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter15, m_axi_gmem0_RVALID, ap_block_state9_io, icmp_ln60_reg_900_pp0_iter14_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter15, m_axi_gmem0_RVALID, ap_block_state9_io, icmp_ln60_reg_900_pp0_iter14_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_io)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state16_pp0_stage0_iter15_assign_proc : process(m_axi_gmem0_RVALID, icmp_ln60_reg_900_pp0_iter14_reg)
    begin
                ap_block_state16_pp0_stage0_iter15 <= ((icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;

        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_io_assign_proc : process(m_axi_gmem0_ARREADY, or_ln58_reg_940_pp0_iter7_reg)
    begin
                ap_block_state9_io <= ((or_ln58_reg_940_pp0_iter7_reg = ap_const_lv1_1) and (m_axi_gmem0_ARREADY = ap_const_logic_0));
    end process;

        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln60_fu_401_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln60_fu_401_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter6_stage0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone, icmp_ln60_reg_900_pp0_iter5_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln60_reg_900_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter6_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter6_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter17_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter17_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_1_phi_fu_340_p4_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0, first_iter_1_reg_335, icmp_ln60_reg_900_pp0_iter3_reg)
    begin
        if (((icmp_ln60_reg_900_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_1_phi_fu_340_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_1_phi_fu_340_p4 <= first_iter_1_reg_335;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_40_fu_465_p2 <= std_logic_vector(unsigned(cy_fu_124) + unsigned(y));
    empty_42_fu_470_p1 <= cy_fu_124(2 - 1 downto 0);
    empty_44_fu_537_p1 <= add_ln61_fu_507_p2(2 - 1 downto 0);
    filterCoeffs_1_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_1_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_2_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_2_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_3_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_3_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_4_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_4_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_5_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_5_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_6_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_6_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_7_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_7_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_8_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_8_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_address0 <= zext_ln58_2_fu_696_p1(8 - 1 downto 0);

    filterCoeffs_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_gmem0_ARREADY, or_ln58_reg_940_pp0_iter7_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln58_reg_940_pp0_iter7_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_AR <= m_axi_gmem0_ARREADY;
        else 
            gmem0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter15, m_axi_gmem0_RVALID, icmp_ln60_reg_900_pp0_iter14_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_371_p_ce <= grp_fu_454_ce;
    grp_fu_371_p_din0 <= iChannel_reg_890;
    grp_fu_371_p_din1 <= inputWidth;
    grp_fu_420_p_ce <= grp_fu_458_ce;
    grp_fu_420_p_din0 <= add_ln60_reg_895;
    grp_fu_420_p_din1 <= inputWidth;
    grp_fu_425_p_ce <= grp_fu_585_ce;
    grp_fu_425_p_din0 <= tmp4_mid1_reg_930;
    grp_fu_425_p_din1 <= inputHeight;

    grp_fu_454_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_454_ce <= ap_const_logic_1;
        else 
            grp_fu_454_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_458_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_458_ce <= ap_const_logic_1;
        else 
            grp_fu_458_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_577_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_577_ce <= ap_const_logic_1;
        else 
            grp_fu_577_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_581_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_581_ce <= ap_const_logic_1;
        else 
            grp_fu_581_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_585_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_585_ce <= ap_const_logic_1;
        else 
            grp_fu_585_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_589_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_589_ce <= ap_const_logic_1;
        else 
            grp_fu_589_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_734_p_ce <= grp_fu_577_ce;
    grp_fu_734_p_din0 <= tmp4_reg_920;
    grp_fu_734_p_din1 <= inputHeight;
    grp_fu_738_p_ce <= grp_fu_581_ce;
    grp_fu_738_p_din0 <= empty_40_reg_925;
    grp_fu_738_p_din1 <= inputWidth;

    grp_fu_758_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_758_ce <= ap_const_logic_1;
        else 
            grp_fu_758_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln60_fu_401_p2 <= "1" when (indvar_flatten161_fu_136 = mul_ln13_1) else "0";
    icmp_ln61_fu_412_p2 <= "1" when (indvar_flatten70_fu_128 = mul_ln13) else "0";
    icmp_ln62_fu_496_p2 <= "1" when (cx_fu_120 = convWidth) else "0";
    m_axi_gmem0_ARADDR <= sext_ln58_fu_680_p1;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= convWidth;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter8, or_ln58_reg_940_pp0_iter7_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln58_reg_940_pp0_iter7_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter15, icmp_ln60_reg_900_pp0_iter14_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln60_reg_900_pp0_iter14_reg = ap_const_lv1_0))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv32_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    or_ln58_1_fu_519_p2 <= (select_ln60_5_fu_501_p3 or icmp_ln61_reg_904_pp0_iter2_reg);
    or_ln58_fu_513_p2 <= (select_ln60_5_fu_501_p3 or or_ln60_fu_484_p2);
    or_ln60_fu_484_p2 <= (icmp_ln61_reg_904_pp0_iter2_reg or ap_phi_mux_first_iter_1_phi_fu_340_p4);
    p_cast10_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_41_reg_967),33));
    p_cast10_mid1117_cast_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_cast10_mid1117),33));
    p_cast10_mid1_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid162_reg_978),33));
    p_mid1_fu_532_p2 <= std_logic_vector(unsigned(add_ln61_fu_507_p2) + unsigned(y));
    select_ln58_1_fu_638_p3 <= 
        tmp5_mid1_fu_632_p2 when (select_ln60_5_reg_935_pp0_iter5_reg(0) = '1') else 
        select_ln60_3_fu_622_p3;
    select_ln58_2_fu_541_p3 <= 
        empty_44_fu_537_p1 when (select_ln60_5_fu_501_p3(0) = '1') else 
        select_ln60_4_fu_489_p3;
    select_ln58_fu_524_p3 <= 
        ap_const_lv32_0 when (or_ln58_1_fu_519_p2(0) = '1') else 
        cx_fu_120;
    select_ln60_1_fu_417_p2 <= iChannel_1_fu_132;
    select_ln60_1_fu_417_p3 <= 
        add_ln60_fu_395_p2 when (icmp_ln61_fu_412_p2(0) = '1') else 
        select_ln60_1_fu_417_p2;
    select_ln60_2_fu_608_p3 <= 
        p_mid1111_reg_972 when (icmp_ln61_reg_904_pp0_iter5_reg(0) = '1') else 
        empty_reg_961;
    select_ln60_3_fu_622_p3 <= 
        tmp5_mid1119_fu_617_p2 when (icmp_ln61_reg_904_pp0_iter5_reg(0) = '1') else 
        tmp5_fu_599_p2;
    select_ln60_4_fu_489_p3 <= 
        ap_const_lv2_0 when (icmp_ln61_reg_904_pp0_iter2_reg(0) = '1') else 
        empty_42_fu_470_p1;
    select_ln60_5_fu_501_p3 <= 
        icmp_ln44_1 when (icmp_ln61_reg_904_pp0_iter2_reg(0) = '1') else 
        icmp_ln62_fu_496_p2;
    select_ln60_fu_477_p3 <= 
        ap_const_lv32_0 when (icmp_ln61_reg_904_pp0_iter2_reg(0) = '1') else 
        cy_fu_124;
    select_ln61_1_fu_431_p3 <= 
        ap_const_lv64_1 when (icmp_ln61_fu_412_p2(0) = '1') else 
        add_ln61_1_fu_425_p2;
    select_ln61_fu_549_p3 <= 
        add_ln61_fu_507_p2 when (select_ln60_5_fu_501_p3(0) = '1') else 
        select_ln60_fu_477_p3;
        sext_ln58_fu_680_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln62_mid2_v_reg_988),64));

    sext_ln62_mid2_v_v_v_v_v_fu_654_p3 <= (add_ln58_reg_983 & ap_const_lv2_0);
    tmp5_fu_599_p2 <= std_logic_vector(unsigned(zext_ln61_fu_593_p1) + unsigned(p_cast10_fu_596_p1));
    tmp5_mid1119_fu_617_p2 <= std_logic_vector(unsigned(zext_ln61_1_fu_605_p1) + unsigned(p_cast10_mid1117_cast_reg_885));
    tmp5_mid1_fu_632_p2 <= std_logic_vector(unsigned(zext_ln60_1_fu_613_p1) + unsigned(p_cast10_mid1_fu_629_p1));
    trunc_ln65_fu_557_p1 <= select_ln58_fu_524_p3(2 - 1 downto 0);
    zext_ln58_1_fu_661_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln62_mid2_v_v_v_v_v_fu_654_p3),64));
    zext_ln58_2_fu_696_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln60_1_reg_915_pp0_iter13_reg),64));
    zext_ln58_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln58_1_fu_638_p3),34));
    zext_ln60_1_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln60_2_fu_608_p3),33));
    zext_ln60_cast_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln60),34));
    zext_ln61_1_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid1111_reg_972),33));
    zext_ln61_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_961),33));
end behav;
