// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conv2D_HW_Conv2D_HW,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020i-clg400-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.584000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=7556,HLS_SYN_LUT=8149,HLS_VERSION=2022_2}" *)

module Conv2D_HW (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [63:0] output_r;
wire   [63:0] coeffs;
wire   [31:0] numChannels;
wire   [31:0] numFilters;
wire   [31:0] inputWidth;
wire   [31:0] inputHeight;
wire   [31:0] convWidth;
wire   [31:0] convHeight;
reg    gmem0_blk_n_AW;
wire    ap_CS_fsm_state14;
reg    gmem0_blk_n_W;
wire    ap_CS_fsm_state17;
reg    gmem0_blk_n_B;
wire    ap_CS_fsm_state22;
reg  signed [31:0] convHeight_read_reg_548;
reg   [31:0] convWidth_read_reg_554;
reg   [31:0] inputHeight_read_reg_563;
reg   [31:0] inputWidth_read_reg_569;
reg   [31:0] numFilters_read_reg_576;
reg   [31:0] numChannels_read_reg_581;
reg   [63:0] coeffs_read_reg_587;
reg   [63:0] output_r_read_reg_592;
reg   [63:0] input_r_read_reg_597;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_353_p2;
reg   [63:0] mul_ln13_reg_618;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [31:0] sub_fu_375_p2;
reg  signed [31:0] sub_reg_635;
wire    ap_CS_fsm_state8;
wire   [31:0] sub41_fu_380_p2;
reg   [31:0] sub41_reg_641;
wire  signed [31:0] grp_fu_371_p2;
reg   [31:0] mul_ln39_reg_649;
wire   [95:0] grp_fu_365_p2;
reg   [95:0] mul_ln13_1_reg_655;
wire   [0:0] icmp_ln44_fu_385_p2;
reg   [0:0] icmp_ln44_reg_661;
wire   [31:0] add_ln39_1_fu_399_p2;
reg   [31:0] add_ln39_1_reg_673;
wire    ap_CS_fsm_state9;
wire   [31:0] add_ln39_2_fu_404_p2;
reg   [31:0] add_ln39_2_reg_678;
wire   [31:0] add_ln39_fu_414_p2;
reg   [31:0] add_ln39_reg_686;
wire   [31:0] grp_fu_420_p2;
reg   [31:0] empty_45_reg_691;
wire    ap_CS_fsm_state10;
wire   [32:0] zext_ln56_fu_429_p1;
reg   [32:0] zext_ln56_reg_697;
wire    ap_CS_fsm_state12;
wire   [31:0] add_ln56_1_fu_433_p2;
reg   [31:0] add_ln56_1_reg_702;
wire    ap_CS_fsm_state13;
wire   [31:0] add_ln56_2_fu_438_p2;
reg   [31:0] add_ln56_2_reg_707;
wire   [31:0] add_ln56_fu_448_p2;
reg   [31:0] add_ln56_reg_715;
reg   [63:0] gmem0_addr_reg_720;
wire   [0:0] icmp_ln56_fu_443_p2;
wire   [31:0] add_ln57_fu_517_p2;
reg   [31:0] add_ln57_reg_729;
wire    ap_CS_fsm_state15;
reg   [7:0] filterCoeffs_address0;
reg    filterCoeffs_ce0;
reg    filterCoeffs_we0;
wire   [31:0] filterCoeffs_q0;
reg   [7:0] filterCoeffs_1_address0;
reg    filterCoeffs_1_ce0;
reg    filterCoeffs_1_we0;
wire   [31:0] filterCoeffs_1_q0;
reg   [7:0] filterCoeffs_2_address0;
reg    filterCoeffs_2_ce0;
reg    filterCoeffs_2_we0;
wire   [31:0] filterCoeffs_2_q0;
reg   [7:0] filterCoeffs_3_address0;
reg    filterCoeffs_3_ce0;
reg    filterCoeffs_3_we0;
wire   [31:0] filterCoeffs_3_q0;
reg   [7:0] filterCoeffs_4_address0;
reg    filterCoeffs_4_ce0;
reg    filterCoeffs_4_we0;
wire   [31:0] filterCoeffs_4_q0;
reg   [7:0] filterCoeffs_5_address0;
reg    filterCoeffs_5_ce0;
reg    filterCoeffs_5_we0;
wire   [31:0] filterCoeffs_5_q0;
reg   [7:0] filterCoeffs_6_address0;
reg    filterCoeffs_6_ce0;
reg    filterCoeffs_6_we0;
wire   [31:0] filterCoeffs_6_q0;
reg   [7:0] filterCoeffs_7_address0;
reg    filterCoeffs_7_ce0;
reg    filterCoeffs_7_we0;
wire   [31:0] filterCoeffs_7_q0;
reg   [7:0] filterCoeffs_8_address0;
reg    filterCoeffs_8_ce0;
reg    filterCoeffs_8_we0;
wire   [31:0] filterCoeffs_8_q0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_idle;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_ready;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWUSER;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WSTRB;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WUSER;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARUSER;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_RREADY;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_BREADY;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_d0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_address0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_ce0;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_we0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_d0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_ce;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_done;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_idle;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_ready;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWUSER;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WSTRB;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WUSER;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARUSER;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_RREADY;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_BREADY;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_1_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_1_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_2_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_2_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_3_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_3_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_4_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_4_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_5_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_5_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_6_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_6_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_7_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_7_ce0;
wire   [7:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_8_address0;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_8_ce0;
wire   [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_acc_out;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_acc_out_ap_vld;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_din1;
wire    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_ce;
reg    gmem0_AWVALID;
wire    gmem0_AWREADY;
reg    gmem0_WVALID;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire   [8:0] gmem0_RFIFONUM;
wire    gmem0_BVALID;
reg    gmem0_BREADY;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
reg    gmem1_ARVALID;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
reg    gmem1_RREADY;
wire   [31:0] gmem1_RDATA;
wire   [8:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
reg   [31:0] y_reg_233;
reg   [31:0] phi_mul_reg_245;
reg   [31:0] phi_mul211_reg_256;
reg   [31:0] x_reg_268;
reg    grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start_reg;
reg   [21:0] ap_NS_fsm;
wire    ap_NS_fsm_state11;
wire    ap_CS_fsm_state11;
reg    grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start_reg;
wire   [0:0] icmp_ln57_fu_512_p2;
wire    ap_CS_fsm_state16;
wire  signed [63:0] sext_ln57_fu_490_p1;
reg   [31:0] phi_mul216_fu_112;
reg   [31:0] phi_mul214_fu_116;
reg   [31:0] iFilter_fu_120;
wire   [31:0] grp_fu_353_p0;
wire   [31:0] grp_fu_353_p1;
wire   [31:0] grp_fu_365_p0;
wire   [63:0] grp_fu_365_p1;
reg  signed [31:0] grp_fu_371_p0;
reg  signed [31:0] grp_fu_371_p1;
wire    ap_CS_fsm_state7;
wire  signed [31:0] add_ln39_1_fu_399_p0;
wire  signed [31:0] add_ln39_2_fu_404_p0;
reg  signed [31:0] grp_fu_420_p0;
reg  signed [31:0] grp_fu_420_p1;
reg  signed [31:0] grp_fu_425_p0;
reg  signed [31:0] grp_fu_425_p1;
wire   [31:0] grp_fu_425_p2;
wire   [32:0] p_cast_fu_454_p1;
wire   [32:0] empty_46_fu_458_p2;
wire   [34:0] tmp_3_fu_463_p3;
wire   [63:0] p_cast12_fu_471_p1;
wire   [63:0] empty_47_fu_475_p2;
wire   [61:0] trunc_ln1_fu_480_p4;
reg    grp_fu_371_ce;
wire   [0:0] icmp_ln39_fu_409_p2;
reg    grp_fu_420_ce;
reg    grp_fu_425_ce;
wire   [31:0] grp_fu_734_p2;
reg  signed [31:0] grp_fu_734_p0;
reg  signed [31:0] grp_fu_734_p1;
reg    grp_fu_734_ce;
wire   [31:0] grp_fu_738_p2;
reg  signed [31:0] grp_fu_738_p0;
reg  signed [31:0] grp_fu_738_p1;
reg    grp_fu_738_ce;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire   [63:0] grp_fu_353_p00;
wire   [63:0] grp_fu_353_p10;
wire   [95:0] grp_fu_365_p00;
wire   [95:0] grp_fu_365_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start_reg = 1'b0;
#0 grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start_reg = 1'b0;
end

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_address0),
    .ce0(filterCoeffs_ce0),
    .we0(filterCoeffs_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_d0),
    .q0(filterCoeffs_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_1_address0),
    .ce0(filterCoeffs_1_ce0),
    .we0(filterCoeffs_1_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_d0),
    .q0(filterCoeffs_1_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_2_address0),
    .ce0(filterCoeffs_2_ce0),
    .we0(filterCoeffs_2_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_d0),
    .q0(filterCoeffs_2_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_3_address0),
    .ce0(filterCoeffs_3_ce0),
    .we0(filterCoeffs_3_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_d0),
    .q0(filterCoeffs_3_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_4_address0),
    .ce0(filterCoeffs_4_ce0),
    .we0(filterCoeffs_4_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_d0),
    .q0(filterCoeffs_4_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_5_address0),
    .ce0(filterCoeffs_5_ce0),
    .we0(filterCoeffs_5_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_d0),
    .q0(filterCoeffs_5_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_6_address0),
    .ce0(filterCoeffs_6_ce0),
    .we0(filterCoeffs_6_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_d0),
    .q0(filterCoeffs_6_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_7_address0),
    .ce0(filterCoeffs_7_ce0),
    .we0(filterCoeffs_7_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_d0),
    .q0(filterCoeffs_7_q0)
);

Conv2D_HW_filterCoeffs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
filterCoeffs_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filterCoeffs_8_address0),
    .ce0(filterCoeffs_8_ce0),
    .we0(filterCoeffs_8_we0),
    .d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_d0),
    .q0(filterCoeffs_8_q0)
);

Conv2D_HW_Conv2D_HW_Pipeline_loop_load_coef_x grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_ready),
    .m_axi_gmem1_AWVALID(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .mul_ln39(mul_ln39_reg_649),
    .convWidth(convWidth_read_reg_554),
    .zext_ln42(empty_45_reg_691),
    .mul_ln13_1(mul_ln13_1_reg_655),
    .filterCoeffs_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_address0),
    .filterCoeffs_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_ce0),
    .filterCoeffs_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_we0),
    .filterCoeffs_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_d0),
    .filterCoeffs_8_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_address0),
    .filterCoeffs_8_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_ce0),
    .filterCoeffs_8_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_we0),
    .filterCoeffs_8_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_d0),
    .filterCoeffs_7_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_address0),
    .filterCoeffs_7_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_ce0),
    .filterCoeffs_7_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_we0),
    .filterCoeffs_7_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_d0),
    .filterCoeffs_6_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_address0),
    .filterCoeffs_6_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_ce0),
    .filterCoeffs_6_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_we0),
    .filterCoeffs_6_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_d0),
    .filterCoeffs_5_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_address0),
    .filterCoeffs_5_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_ce0),
    .filterCoeffs_5_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_we0),
    .filterCoeffs_5_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_d0),
    .filterCoeffs_4_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_address0),
    .filterCoeffs_4_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_ce0),
    .filterCoeffs_4_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_we0),
    .filterCoeffs_4_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_d0),
    .filterCoeffs_3_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_address0),
    .filterCoeffs_3_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_ce0),
    .filterCoeffs_3_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_we0),
    .filterCoeffs_3_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_d0),
    .filterCoeffs_2_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_address0),
    .filterCoeffs_2_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_ce0),
    .filterCoeffs_2_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_we0),
    .filterCoeffs_2_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_d0),
    .filterCoeffs_1_address0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_address0),
    .filterCoeffs_1_ce0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_ce0),
    .filterCoeffs_1_we0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_we0),
    .filterCoeffs_1_d0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_d0),
    .mul_ln13(mul_ln13_reg_618),
    .zext_ln43_3(empty_45_reg_691),
    .icmp_ln44_1(icmp_ln44_reg_661),
    .coeffs(coeffs_read_reg_587),
    .grp_fu_371_p_din0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_din0),
    .grp_fu_371_p_din1(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_din1),
    .grp_fu_371_p_dout0(grp_fu_371_p2),
    .grp_fu_371_p_ce(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_ce),
    .grp_fu_420_p_din0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_din0),
    .grp_fu_420_p_din1(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_din1),
    .grp_fu_420_p_dout0(grp_fu_420_p2),
    .grp_fu_420_p_ce(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_ce),
    .grp_fu_734_p_din0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_din0),
    .grp_fu_734_p_din1(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_din1),
    .grp_fu_734_p_dout0(grp_fu_734_p2),
    .grp_fu_734_p_ce(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_ce),
    .grp_fu_738_p_din0(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_din0),
    .grp_fu_738_p_din1(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_din1),
    .grp_fu_738_p_dout0(grp_fu_738_p2),
    .grp_fu_738_p_ce(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_ce)
);

Conv2D_HW_Conv2D_HW_Pipeline_loop_acc_x grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_ready),
    .m_axi_gmem0_AWVALID(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .inputWidth(inputWidth_read_reg_569),
    .inputHeight(inputHeight_read_reg_563),
    .y(y_reg_233),
    .mul_ln13_1(mul_ln13_1_reg_655),
    .convWidth(convWidth_read_reg_554),
    .mul_ln13(mul_ln13_reg_618),
    .p_cast10_mid1117(phi_mul211_reg_256),
    .icmp_ln44_1(icmp_ln44_reg_661),
    .zext_ln60(x_reg_268),
    .input_r(input_r_read_reg_597),
    .filterCoeffs_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_address0),
    .filterCoeffs_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_ce0),
    .filterCoeffs_q0(filterCoeffs_q0),
    .filterCoeffs_1_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_1_address0),
    .filterCoeffs_1_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_1_ce0),
    .filterCoeffs_1_q0(filterCoeffs_1_q0),
    .filterCoeffs_2_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_2_address0),
    .filterCoeffs_2_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_2_ce0),
    .filterCoeffs_2_q0(filterCoeffs_2_q0),
    .filterCoeffs_3_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_3_address0),
    .filterCoeffs_3_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_3_ce0),
    .filterCoeffs_3_q0(filterCoeffs_3_q0),
    .filterCoeffs_4_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_4_address0),
    .filterCoeffs_4_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_4_ce0),
    .filterCoeffs_4_q0(filterCoeffs_4_q0),
    .filterCoeffs_5_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_5_address0),
    .filterCoeffs_5_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_5_ce0),
    .filterCoeffs_5_q0(filterCoeffs_5_q0),
    .filterCoeffs_6_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_6_address0),
    .filterCoeffs_6_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_6_ce0),
    .filterCoeffs_6_q0(filterCoeffs_6_q0),
    .filterCoeffs_7_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_7_address0),
    .filterCoeffs_7_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_7_ce0),
    .filterCoeffs_7_q0(filterCoeffs_7_q0),
    .filterCoeffs_8_address0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_8_address0),
    .filterCoeffs_8_ce0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_8_ce0),
    .filterCoeffs_8_q0(filterCoeffs_8_q0),
    .acc_out(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_acc_out),
    .acc_out_ap_vld(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_acc_out_ap_vld),
    .grp_fu_371_p_din0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_din0),
    .grp_fu_371_p_din1(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_din1),
    .grp_fu_371_p_dout0(grp_fu_371_p2),
    .grp_fu_371_p_ce(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_ce),
    .grp_fu_420_p_din0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_din0),
    .grp_fu_420_p_din1(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_din1),
    .grp_fu_420_p_dout0(grp_fu_420_p2),
    .grp_fu_420_p_ce(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_ce),
    .grp_fu_734_p_din0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_din0),
    .grp_fu_734_p_din1(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_din1),
    .grp_fu_734_p_dout0(grp_fu_734_p2),
    .grp_fu_734_p_ce(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_ce),
    .grp_fu_738_p_din0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_din0),
    .grp_fu_738_p_din1(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_din1),
    .grp_fu_738_p_dout0(grp_fu_738_p2),
    .grp_fu_738_p_ce(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_ce),
    .grp_fu_425_p_din0(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_din0),
    .grp_fu_425_p_din1(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_din1),
    .grp_fu_425_p_dout0(grp_fu_425_p2),
    .grp_fu_425_p_ce(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_ce)
);

Conv2D_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .coeffs(coeffs),
    .numChannels(numChannels),
    .numFilters(numFilters),
    .inputWidth(inputWidth),
    .inputHeight(inputHeight),
    .convWidth(convWidth),
    .convHeight(convHeight),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Conv2D_HW_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARADDR),
    .I_ARLEN(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARLEN),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(gmem0_AWVALID),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(gmem0_addr_reg_720),
    .I_AWLEN(sub41_reg_641),
    .I_WVALID(gmem0_WVALID),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_acc_out),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(gmem0_BREADY)
);

Conv2D_HW_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARADDR),
    .I_ARLEN(grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARLEN),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U57(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_353_p0),
    .din1(grp_fu_353_p1),
    .ce(1'b1),
    .dout(grp_fu_353_p2)
);

Conv2D_HW_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U58(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_365_p0),
    .din1(grp_fu_365_p1),
    .ce(1'b1),
    .dout(grp_fu_365_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U59(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_371_p0),
    .din1(grp_fu_371_p1),
    .ce(grp_fu_371_ce),
    .dout(grp_fu_371_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U60(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_420_p0),
    .din1(grp_fu_420_p1),
    .ce(grp_fu_420_ce),
    .dout(grp_fu_420_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U61(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_425_p0),
    .din1(grp_fu_425_p1),
    .ce(grp_fu_425_ce),
    .dout(grp_fu_425_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U62(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_734_p0),
    .din1(grp_fu_734_p1),
    .ce(grp_fu_734_ce),
    .dout(grp_fu_734_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U63(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_738_p0),
    .din1(grp_fu_738_p1),
    .ce(grp_fu_738_ce),
    .dout(grp_fu_738_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln57_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
            grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state11) & (1'b1 == ap_CS_fsm_state10))) begin
            grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iFilter_fu_120 <= 32'd0;
    end else if (((icmp_ln56_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        iFilter_fu_120 <= add_ln39_reg_686;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        phi_mul211_reg_256 <= 32'd0;
    end else if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        phi_mul211_reg_256 <= add_ln56_1_reg_702;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul214_fu_116 <= 32'd0;
    end else if (((icmp_ln56_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        phi_mul214_fu_116 <= add_ln39_2_reg_678;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul216_fu_112 <= 32'd0;
    end else if (((icmp_ln56_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        phi_mul216_fu_112 <= add_ln39_1_reg_673;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        phi_mul_reg_245 <= 32'd0;
    end else if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        phi_mul_reg_245 <= add_ln56_2_reg_707;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        x_reg_268 <= 32'd0;
    end else if (((gmem0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        x_reg_268 <= add_ln57_reg_729;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        y_reg_233 <= 32'd0;
    end else if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        y_reg_233 <= add_ln56_reg_715;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln39_1_reg_673 <= add_ln39_1_fu_399_p2;
        add_ln39_2_reg_678 <= add_ln39_2_fu_404_p2;
        add_ln39_reg_686 <= add_ln39_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln56_1_reg_702 <= add_ln56_1_fu_433_p2;
        add_ln56_2_reg_707 <= add_ln56_2_fu_438_p2;
        add_ln56_reg_715 <= add_ln56_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln57_reg_729 <= add_ln57_fu_517_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coeffs_read_reg_587 <= coeffs;
        convHeight_read_reg_548 <= convHeight;
        convWidth_read_reg_554 <= convWidth;
        inputHeight_read_reg_563 <= inputHeight;
        inputWidth_read_reg_569 <= inputWidth;
        input_r_read_reg_597 <= input_r;
        numChannels_read_reg_581 <= numChannels;
        numFilters_read_reg_576 <= numFilters;
        output_r_read_reg_592 <= output_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        empty_45_reg_691 <= grp_fu_420_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_443_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        gmem0_addr_reg_720 <= sext_ln57_fu_490_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        icmp_ln44_reg_661 <= icmp_ln44_fu_385_p2;
        mul_ln13_1_reg_655 <= grp_fu_365_p2;
        mul_ln39_reg_649 <= grp_fu_371_p2;
        sub41_reg_641 <= sub41_fu_380_p2;
        sub_reg_635 <= sub_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln13_reg_618 <= grp_fu_353_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        zext_ln56_reg_697[31 : 0] <= zext_ln56_fu_429_p1[31 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((gmem0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_WREADY == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((gmem0_BVALID == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln39_fu_409_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_409_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_1_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_1_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_address0;
    end else begin
        filterCoeffs_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_1_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_1_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_ce0;
    end else begin
        filterCoeffs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_1_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_1_we0;
    end else begin
        filterCoeffs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_2_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_2_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_address0;
    end else begin
        filterCoeffs_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_2_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_2_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_ce0;
    end else begin
        filterCoeffs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_2_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_2_we0;
    end else begin
        filterCoeffs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_3_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_3_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_address0;
    end else begin
        filterCoeffs_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_3_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_3_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_ce0;
    end else begin
        filterCoeffs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_3_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_3_we0;
    end else begin
        filterCoeffs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_4_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_4_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_address0;
    end else begin
        filterCoeffs_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_4_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_4_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_ce0;
    end else begin
        filterCoeffs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_4_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_4_we0;
    end else begin
        filterCoeffs_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_5_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_5_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_address0;
    end else begin
        filterCoeffs_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_5_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_5_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_ce0;
    end else begin
        filterCoeffs_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_5_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_5_we0;
    end else begin
        filterCoeffs_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_6_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_6_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_address0;
    end else begin
        filterCoeffs_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_6_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_6_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_ce0;
    end else begin
        filterCoeffs_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_6_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_6_we0;
    end else begin
        filterCoeffs_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_7_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_7_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_address0;
    end else begin
        filterCoeffs_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_7_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_7_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_ce0;
    end else begin
        filterCoeffs_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_7_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_7_we0;
    end else begin
        filterCoeffs_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_8_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_8_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_address0;
    end else begin
        filterCoeffs_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_8_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_8_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_ce0;
    end else begin
        filterCoeffs_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_8_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_8_we0;
    end else begin
        filterCoeffs_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_address0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_address0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_address0;
    end else begin
        filterCoeffs_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        filterCoeffs_ce0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_filterCoeffs_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_ce0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_ce0;
    end else begin
        filterCoeffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        filterCoeffs_we0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_filterCoeffs_we0;
    end else begin
        filterCoeffs_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((icmp_ln57_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        gmem0_ARVALID = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        gmem0_AWVALID = 1'b1;
    end else begin
        gmem0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        gmem0_BREADY = 1'b1;
    end else begin
        gmem0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((icmp_ln57_fu_512_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15)))) begin
        gmem0_RREADY = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        gmem0_WVALID = 1'b1;
    end else begin
        gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gmem0_blk_n_AW = m_axi_gmem0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        gmem0_blk_n_B = m_axi_gmem0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        gmem0_blk_n_W = m_axi_gmem0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem1_ARVALID = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_ARVALID;
    end else begin
        gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        gmem1_RREADY = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_m_axi_gmem1_RREADY;
    end else begin
        gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_ce = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_371_ce = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_ce;
    end else begin
        grp_fu_371_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_p0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_371_p0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_371_p0 = convHeight_read_reg_548;
    end else begin
        grp_fu_371_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_371_p1 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_371_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_371_p1 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_371_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_371_p1 = convWidth_read_reg_554;
    end else begin
        grp_fu_371_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_420_ce = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_420_ce = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_ce;
    end else begin
        grp_fu_420_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_420_p0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_420_p0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_420_p0 = phi_mul216_fu_112;
    end else begin
        grp_fu_420_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_420_p1 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_420_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_420_p1 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_420_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_420_p1 = mul_ln39_reg_649;
    end else begin
        grp_fu_420_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_425_ce = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_fu_425_ce = 1'b1;
    end else begin
        grp_fu_425_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_425_p0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_425_p0 = phi_mul214_fu_116;
    end else begin
        grp_fu_425_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_425_p1 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_425_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_425_p1 = sub_reg_635;
    end else begin
        grp_fu_425_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_734_ce = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_734_ce = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_ce;
    end else begin
        grp_fu_734_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_734_p0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_734_p0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_din0;
    end else begin
        grp_fu_734_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_734_p1 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_734_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_734_p1 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_734_p_din1;
    end else begin
        grp_fu_734_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_738_ce = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_738_ce = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_ce;
    end else begin
        grp_fu_738_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_738_p0 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_738_p0 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_din0;
    end else begin
        grp_fu_738_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_738_p1 = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_grp_fu_738_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_738_p1 = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_grp_fu_738_p_din1;
    end else begin
        grp_fu_738_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln39_fu_409_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((icmp_ln56_fu_443_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((gmem0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln57_fu_512_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((gmem0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((gmem0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_1_fu_399_p0 = phi_mul216_fu_112;

assign add_ln39_1_fu_399_p2 = ($signed(add_ln39_1_fu_399_p0) + $signed(numChannels_read_reg_581));

assign add_ln39_2_fu_404_p0 = phi_mul214_fu_116;

assign add_ln39_2_fu_404_p2 = ($signed(add_ln39_2_fu_404_p0) + $signed(sub41_reg_641));

assign add_ln39_fu_414_p2 = (iFilter_fu_120 + 32'd1);

assign add_ln56_1_fu_433_p2 = (phi_mul211_reg_256 + inputWidth_read_reg_569);

assign add_ln56_2_fu_438_p2 = (phi_mul_reg_245 + sub41_reg_641);

assign add_ln56_fu_448_p2 = (y_reg_233 + 32'd1);

assign add_ln57_fu_517_p2 = (x_reg_268 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state11 = ap_NS_fsm[32'd10];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_46_fu_458_p2 = (p_cast_fu_454_p1 + zext_ln56_reg_697);

assign empty_47_fu_475_p2 = (p_cast12_fu_471_p1 + output_r_read_reg_592);

assign grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start = grp_Conv2D_HW_Pipeline_loop_acc_x_fu_303_ap_start_reg;

assign grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start = grp_Conv2D_HW_Pipeline_loop_load_coef_x_fu_280_ap_start_reg;

assign grp_fu_353_p0 = grp_fu_353_p00;

assign grp_fu_353_p00 = $unsigned(convHeight_read_reg_548);

assign grp_fu_353_p1 = grp_fu_353_p10;

assign grp_fu_353_p10 = convWidth_read_reg_554;

assign grp_fu_365_p0 = grp_fu_365_p00;

assign grp_fu_365_p00 = numChannels_read_reg_581;

assign grp_fu_365_p1 = grp_fu_365_p10;

assign grp_fu_365_p10 = mul_ln13_reg_618;

assign icmp_ln39_fu_409_p2 = ((iFilter_fu_120 == numFilters_read_reg_576) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_385_p2 = ((convWidth_read_reg_554 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_443_p2 = ((y_reg_233 == sub_reg_635) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_512_p2 = ((x_reg_268 == sub41_reg_641) ? 1'b1 : 1'b0);

assign p_cast12_fu_471_p1 = tmp_3_fu_463_p3;

assign p_cast_fu_454_p1 = phi_mul_reg_245;

assign sext_ln57_fu_490_p1 = $signed(trunc_ln1_fu_480_p4);

assign sub41_fu_380_p2 = ($signed(inputWidth_read_reg_569) + $signed(32'd4294967294));

assign sub_fu_375_p2 = ($signed(inputHeight_read_reg_563) + $signed(32'd4294967294));

assign tmp_3_fu_463_p3 = {{empty_46_fu_458_p2}, {2'd0}};

assign trunc_ln1_fu_480_p4 = {{empty_47_fu_475_p2[63:2]}};

assign zext_ln56_fu_429_p1 = grp_fu_425_p2;

always @ (posedge ap_clk) begin
    zext_ln56_reg_697[32] <= 1'b0;
end

endmodule //Conv2D_HW
