// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv2D_HW_Conv2D_HW_Pipeline_loop_load_coef_x (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        mul_ln39,
        convWidth,
        zext_ln42,
        mul_ln13_1,
        filterCoeffs_address0,
        filterCoeffs_ce0,
        filterCoeffs_we0,
        filterCoeffs_d0,
        filterCoeffs_8_address0,
        filterCoeffs_8_ce0,
        filterCoeffs_8_we0,
        filterCoeffs_8_d0,
        filterCoeffs_7_address0,
        filterCoeffs_7_ce0,
        filterCoeffs_7_we0,
        filterCoeffs_7_d0,
        filterCoeffs_6_address0,
        filterCoeffs_6_ce0,
        filterCoeffs_6_we0,
        filterCoeffs_6_d0,
        filterCoeffs_5_address0,
        filterCoeffs_5_ce0,
        filterCoeffs_5_we0,
        filterCoeffs_5_d0,
        filterCoeffs_4_address0,
        filterCoeffs_4_ce0,
        filterCoeffs_4_we0,
        filterCoeffs_4_d0,
        filterCoeffs_3_address0,
        filterCoeffs_3_ce0,
        filterCoeffs_3_we0,
        filterCoeffs_3_d0,
        filterCoeffs_2_address0,
        filterCoeffs_2_ce0,
        filterCoeffs_2_we0,
        filterCoeffs_2_d0,
        filterCoeffs_1_address0,
        filterCoeffs_1_ce0,
        filterCoeffs_1_we0,
        filterCoeffs_1_d0,
        mul_ln13,
        zext_ln43_3,
        icmp_ln44_1,
        coeffs,
        grp_fu_371_p_din0,
        grp_fu_371_p_din1,
        grp_fu_371_p_dout0,
        grp_fu_371_p_ce,
        grp_fu_420_p_din0,
        grp_fu_420_p_din1,
        grp_fu_420_p_dout0,
        grp_fu_420_p_ce,
        grp_fu_734_p_din0,
        grp_fu_734_p_din1,
        grp_fu_734_p_dout0,
        grp_fu_734_p_ce,
        grp_fu_738_p_din0,
        grp_fu_738_p_din1,
        grp_fu_738_p_dout0,
        grp_fu_738_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [31:0] m_axi_gmem1_WDATA;
output  [3:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [31:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [31:0] mul_ln39;
input  [31:0] convWidth;
input  [31:0] zext_ln42;
input  [95:0] mul_ln13_1;
output  [7:0] filterCoeffs_address0;
output   filterCoeffs_ce0;
output   filterCoeffs_we0;
output  [31:0] filterCoeffs_d0;
output  [7:0] filterCoeffs_8_address0;
output   filterCoeffs_8_ce0;
output   filterCoeffs_8_we0;
output  [31:0] filterCoeffs_8_d0;
output  [7:0] filterCoeffs_7_address0;
output   filterCoeffs_7_ce0;
output   filterCoeffs_7_we0;
output  [31:0] filterCoeffs_7_d0;
output  [7:0] filterCoeffs_6_address0;
output   filterCoeffs_6_ce0;
output   filterCoeffs_6_we0;
output  [31:0] filterCoeffs_6_d0;
output  [7:0] filterCoeffs_5_address0;
output   filterCoeffs_5_ce0;
output   filterCoeffs_5_we0;
output  [31:0] filterCoeffs_5_d0;
output  [7:0] filterCoeffs_4_address0;
output   filterCoeffs_4_ce0;
output   filterCoeffs_4_we0;
output  [31:0] filterCoeffs_4_d0;
output  [7:0] filterCoeffs_3_address0;
output   filterCoeffs_3_ce0;
output   filterCoeffs_3_we0;
output  [31:0] filterCoeffs_3_d0;
output  [7:0] filterCoeffs_2_address0;
output   filterCoeffs_2_ce0;
output   filterCoeffs_2_we0;
output  [31:0] filterCoeffs_2_d0;
output  [7:0] filterCoeffs_1_address0;
output   filterCoeffs_1_ce0;
output   filterCoeffs_1_we0;
output  [31:0] filterCoeffs_1_d0;
input  [63:0] mul_ln13;
input  [31:0] zext_ln43_3;
input  [0:0] icmp_ln44_1;
input  [63:0] coeffs;
output  [31:0] grp_fu_371_p_din0;
output  [31:0] grp_fu_371_p_din1;
input  [31:0] grp_fu_371_p_dout0;
output   grp_fu_371_p_ce;
output  [31:0] grp_fu_420_p_din0;
output  [31:0] grp_fu_420_p_din1;
input  [31:0] grp_fu_420_p_dout0;
output   grp_fu_420_p_ce;
output  [31:0] grp_fu_734_p_din0;
output  [31:0] grp_fu_734_p_din1;
input  [31:0] grp_fu_734_p_dout0;
output   grp_fu_734_p_ce;
output  [31:0] grp_fu_738_p_din0;
output  [31:0] grp_fu_738_p_din1;
input  [31:0] grp_fu_738_p_dout0;
output   grp_fu_738_p_ce;

reg ap_idle;
reg m_axi_gmem1_ARVALID;
reg m_axi_gmem1_RREADY;
reg filterCoeffs_ce0;
reg filterCoeffs_we0;
reg filterCoeffs_8_ce0;
reg filterCoeffs_8_we0;
reg filterCoeffs_7_ce0;
reg filterCoeffs_7_we0;
reg filterCoeffs_6_ce0;
reg filterCoeffs_6_we0;
reg filterCoeffs_5_ce0;
reg filterCoeffs_5_we0;
reg filterCoeffs_4_ce0;
reg filterCoeffs_4_we0;
reg filterCoeffs_3_ce0;
reg filterCoeffs_3_we0;
reg filterCoeffs_2_ce0;
reg filterCoeffs_2_we0;
reg filterCoeffs_1_ce0;
reg filterCoeffs_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg   [0:0] or_ln43_reg_771;
reg   [0:0] or_ln43_reg_771_pp0_iter6_reg;
reg    ap_block_state8_io;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
reg    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln42_fu_350_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem1_blk_n_AR;
reg   [0:0] first_iter_0_reg_298;
reg    ap_block_pp0_stage0_11001;
wire   [32:0] zext_ln42_cast_fu_311_p1;
reg   [32:0] zext_ln42_cast_reg_729;
wire   [32:0] zext_ln43_3_cast_fu_315_p1;
reg   [32:0] zext_ln43_3_cast_reg_735;
reg   [0:0] icmp_ln42_reg_740;
reg   [0:0] icmp_ln42_reg_740_pp0_iter2_reg;
reg   [0:0] icmp_ln42_reg_740_pp0_iter3_reg;
reg   [0:0] icmp_ln42_reg_740_pp0_iter4_reg;
reg   [0:0] icmp_ln42_reg_740_pp0_iter5_reg;
wire   [0:0] icmp_ln43_fu_361_p2;
reg   [0:0] icmp_ln43_reg_744;
reg   [0:0] icmp_ln43_reg_744_pp0_iter2_reg;
reg   [0:0] icmp_ln43_reg_744_pp0_iter3_reg;
reg   [0:0] icmp_ln43_reg_744_pp0_iter4_reg;
reg   [0:0] icmp_ln43_reg_744_pp0_iter5_reg;
reg  signed [31:0] y_1_reg_756;
wire   [0:0] select_ln42_4_fu_424_p3;
reg   [0:0] select_ln42_4_reg_761;
reg   [0:0] select_ln42_4_reg_761_pp0_iter3_reg;
reg   [0:0] select_ln42_4_reg_761_pp0_iter4_reg;
reg   [0:0] select_ln42_4_reg_761_pp0_iter5_reg;
wire  signed [31:0] add_ln43_3_fu_430_p2;
reg  signed [31:0] add_ln43_3_reg_766;
wire   [0:0] or_ln43_fu_436_p2;
reg   [0:0] or_ln43_reg_771_pp0_iter3_reg;
reg   [0:0] or_ln43_reg_771_pp0_iter4_reg;
reg   [0:0] or_ln43_reg_771_pp0_iter5_reg;
wire   [1:0] select_ln43_2_fu_459_p3;
reg   [1:0] select_ln43_2_reg_775;
reg   [1:0] select_ln43_2_reg_775_pp0_iter3_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter4_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter5_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter6_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter7_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter8_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter9_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter10_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter11_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter12_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter13_reg;
reg   [1:0] select_ln43_2_reg_775_pp0_iter14_reg;
wire   [1:0] trunc_ln46_fu_475_p1;
reg   [1:0] trunc_ln46_reg_779;
reg   [1:0] trunc_ln46_reg_779_pp0_iter3_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter4_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter5_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter6_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter7_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter8_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter9_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter10_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter11_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter12_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter13_reg;
reg   [1:0] trunc_ln46_reg_779_pp0_iter14_reg;
wire  signed [31:0] add_ln42_fu_507_p2;
reg  signed [31:0] add_ln42_reg_788;
wire   [31:0] select_ln42_1_fu_513_p3;
reg   [31:0] select_ln42_1_reg_793;
reg   [31:0] select_ln42_1_reg_793_pp0_iter4_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter5_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter6_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter7_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter8_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter9_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter10_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter11_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter12_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter13_reg;
reg   [31:0] select_ln42_1_reg_793_pp0_iter14_reg;
reg   [31:0] mul_ln42_reg_798;
reg   [31:0] mul_ln42_reg_798_pp0_iter5_reg;
reg   [31:0] mul_ln43_reg_804;
reg   [31:0] mul_ln43_1_reg_809;
wire   [32:0] add_ln43_fu_536_p2;
reg   [32:0] add_ln43_reg_814;
reg   [31:0] mul_ln42_1_reg_819;
wire   [32:0] add_ln43_4_fu_544_p2;
reg   [32:0] add_ln43_4_reg_825;
reg   [61:0] sext_ln44_mid2_v_reg_830;
reg   [31:0] gmem1_addr_1_read_reg_845;
reg    ap_condition_exit_pp0_iter6_stage0;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_303_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln42_1_fu_648_p1;
wire  signed [63:0] sext_ln43_fu_632_p1;
reg   [31:0] x_fu_102;
wire   [31:0] add_ln44_fu_479_p2;
reg   [31:0] y_fu_106;
wire   [31:0] select_ln43_3_fu_467_p3;
reg   [63:0] indvar_flatten_fu_110;
wire   [63:0] select_ln43_4_fu_372_p3;
reg   [31:0] iChannel_fu_114;
reg   [95:0] indvar_flatten49_fu_118;
wire   [95:0] add_ln42_1_fu_355_p2;
wire   [63:0] add_ln43_7_fu_366_p2;
wire  signed [31:0] empty_fu_393_p0;
wire  signed [31:0] select_ln42_fu_400_p2;
wire   [1:0] empty_fu_393_p1;
wire  signed [31:0] icmp_ln44_fu_419_p1;
wire   [0:0] icmp_ln44_fu_419_p2;
wire   [31:0] select_ln42_fu_400_p3;
wire   [0:0] or_ln42_fu_407_p2;
wire   [0:0] or_ln43_1_fu_442_p2;
wire   [1:0] empty_39_fu_455_p1;
wire   [1:0] select_ln42_3_fu_412_p3;
wire   [31:0] select_ln43_fu_447_p3;
wire  signed [31:0] add_ln42_fu_507_p0;
wire  signed [31:0] select_ln42_1_fu_513_p2;
wire   [32:0] zext_ln43_1_fu_533_p1;
wire   [32:0] zext_ln43_5_fu_541_p1;
wire   [33:0] zext_ln43_2_fu_552_p1;
wire   [33:0] zext_ln43_fu_549_p1;
wire   [31:0] select_ln42_2_fu_564_p3;
wire   [32:0] zext_ln42_3_fu_561_p1;
wire   [32:0] add_ln43_2_fu_573_p2;
wire   [33:0] zext_ln43_6_fu_582_p1;
wire   [33:0] zext_ln42_2_fu_569_p1;
wire   [33:0] zext_ln43_4_fu_578_p1;
wire   [33:0] add_ln43_1_fu_555_p2;
wire   [33:0] add_ln43_5_fu_585_p2;
wire   [33:0] select_ln42_5_fu_591_p3;
wire   [33:0] select_ln43_1_fu_598_p3;
wire   [35:0] sext_ln44_mid2_v_v_v_v_v_fu_605_p3;
wire   [63:0] zext_ln43_7_fu_613_p1;
wire   [63:0] add_ln43_6_fu_617_p2;
reg    grp_fu_498_ce;
reg    grp_fu_503_ce;
reg    grp_fu_520_ce;
reg    grp_fu_529_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_done_reg = 1'b0;
end

Conv2D_HW_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter14_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter6_stage0)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_740_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_298 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_298 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            iChannel_fu_114 <= 32'd0;
        end else if (((icmp_ln42_reg_740_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            iChannel_fu_114 <= select_ln42_1_fu_513_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten49_fu_118 <= 96'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_fu_350_p2 == 1'd0))) begin
            indvar_flatten49_fu_118 <= add_ln42_1_fu_355_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_110 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_fu_350_p2 == 1'd0))) begin
            indvar_flatten_fu_110 <= select_ln43_4_fu_372_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            x_fu_102 <= 32'd0;
        end else if (((icmp_ln42_reg_740 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            x_fu_102 <= add_ln44_fu_479_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            y_fu_106 <= 32'd0;
        end else if (((icmp_ln42_reg_740 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            y_fu_106 <= select_ln43_3_fu_467_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln42_reg_788 <= add_ln42_fu_507_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem1_addr_1_read_reg_845 <= m_axi_gmem1_RDATA;
        icmp_ln42_reg_740_pp0_iter2_reg <= icmp_ln42_reg_740;
        icmp_ln42_reg_740_pp0_iter3_reg <= icmp_ln42_reg_740_pp0_iter2_reg;
        icmp_ln42_reg_740_pp0_iter4_reg <= icmp_ln42_reg_740_pp0_iter3_reg;
        icmp_ln42_reg_740_pp0_iter5_reg <= icmp_ln42_reg_740_pp0_iter4_reg;
        icmp_ln43_reg_744_pp0_iter2_reg <= icmp_ln43_reg_744;
        icmp_ln43_reg_744_pp0_iter3_reg <= icmp_ln43_reg_744_pp0_iter2_reg;
        icmp_ln43_reg_744_pp0_iter4_reg <= icmp_ln43_reg_744_pp0_iter3_reg;
        icmp_ln43_reg_744_pp0_iter5_reg <= icmp_ln43_reg_744_pp0_iter4_reg;
        mul_ln42_reg_798 <= grp_fu_371_p_dout0;
        mul_ln42_reg_798_pp0_iter5_reg <= mul_ln42_reg_798;
        or_ln43_reg_771_pp0_iter3_reg <= or_ln43_reg_771;
        or_ln43_reg_771_pp0_iter4_reg <= or_ln43_reg_771_pp0_iter3_reg;
        or_ln43_reg_771_pp0_iter5_reg <= or_ln43_reg_771_pp0_iter4_reg;
        or_ln43_reg_771_pp0_iter6_reg <= or_ln43_reg_771_pp0_iter5_reg;
        select_ln42_1_reg_793_pp0_iter10_reg <= select_ln42_1_reg_793_pp0_iter9_reg;
        select_ln42_1_reg_793_pp0_iter11_reg <= select_ln42_1_reg_793_pp0_iter10_reg;
        select_ln42_1_reg_793_pp0_iter12_reg <= select_ln42_1_reg_793_pp0_iter11_reg;
        select_ln42_1_reg_793_pp0_iter13_reg <= select_ln42_1_reg_793_pp0_iter12_reg;
        select_ln42_1_reg_793_pp0_iter14_reg <= select_ln42_1_reg_793_pp0_iter13_reg;
        select_ln42_1_reg_793_pp0_iter4_reg <= select_ln42_1_reg_793;
        select_ln42_1_reg_793_pp0_iter5_reg <= select_ln42_1_reg_793_pp0_iter4_reg;
        select_ln42_1_reg_793_pp0_iter6_reg <= select_ln42_1_reg_793_pp0_iter5_reg;
        select_ln42_1_reg_793_pp0_iter7_reg <= select_ln42_1_reg_793_pp0_iter6_reg;
        select_ln42_1_reg_793_pp0_iter8_reg <= select_ln42_1_reg_793_pp0_iter7_reg;
        select_ln42_1_reg_793_pp0_iter9_reg <= select_ln42_1_reg_793_pp0_iter8_reg;
        select_ln42_4_reg_761_pp0_iter3_reg <= select_ln42_4_reg_761;
        select_ln42_4_reg_761_pp0_iter4_reg <= select_ln42_4_reg_761_pp0_iter3_reg;
        select_ln42_4_reg_761_pp0_iter5_reg <= select_ln42_4_reg_761_pp0_iter4_reg;
        select_ln43_2_reg_775_pp0_iter10_reg <= select_ln43_2_reg_775_pp0_iter9_reg;
        select_ln43_2_reg_775_pp0_iter11_reg <= select_ln43_2_reg_775_pp0_iter10_reg;
        select_ln43_2_reg_775_pp0_iter12_reg <= select_ln43_2_reg_775_pp0_iter11_reg;
        select_ln43_2_reg_775_pp0_iter13_reg <= select_ln43_2_reg_775_pp0_iter12_reg;
        select_ln43_2_reg_775_pp0_iter14_reg <= select_ln43_2_reg_775_pp0_iter13_reg;
        select_ln43_2_reg_775_pp0_iter3_reg <= select_ln43_2_reg_775;
        select_ln43_2_reg_775_pp0_iter4_reg <= select_ln43_2_reg_775_pp0_iter3_reg;
        select_ln43_2_reg_775_pp0_iter5_reg <= select_ln43_2_reg_775_pp0_iter4_reg;
        select_ln43_2_reg_775_pp0_iter6_reg <= select_ln43_2_reg_775_pp0_iter5_reg;
        select_ln43_2_reg_775_pp0_iter7_reg <= select_ln43_2_reg_775_pp0_iter6_reg;
        select_ln43_2_reg_775_pp0_iter8_reg <= select_ln43_2_reg_775_pp0_iter7_reg;
        select_ln43_2_reg_775_pp0_iter9_reg <= select_ln43_2_reg_775_pp0_iter8_reg;
        trunc_ln46_reg_779_pp0_iter10_reg <= trunc_ln46_reg_779_pp0_iter9_reg;
        trunc_ln46_reg_779_pp0_iter11_reg <= trunc_ln46_reg_779_pp0_iter10_reg;
        trunc_ln46_reg_779_pp0_iter12_reg <= trunc_ln46_reg_779_pp0_iter11_reg;
        trunc_ln46_reg_779_pp0_iter13_reg <= trunc_ln46_reg_779_pp0_iter12_reg;
        trunc_ln46_reg_779_pp0_iter14_reg <= trunc_ln46_reg_779_pp0_iter13_reg;
        trunc_ln46_reg_779_pp0_iter3_reg <= trunc_ln46_reg_779;
        trunc_ln46_reg_779_pp0_iter4_reg <= trunc_ln46_reg_779_pp0_iter3_reg;
        trunc_ln46_reg_779_pp0_iter5_reg <= trunc_ln46_reg_779_pp0_iter4_reg;
        trunc_ln46_reg_779_pp0_iter6_reg <= trunc_ln46_reg_779_pp0_iter5_reg;
        trunc_ln46_reg_779_pp0_iter7_reg <= trunc_ln46_reg_779_pp0_iter6_reg;
        trunc_ln46_reg_779_pp0_iter8_reg <= trunc_ln46_reg_779_pp0_iter7_reg;
        trunc_ln46_reg_779_pp0_iter9_reg <= trunc_ln46_reg_779_pp0_iter8_reg;
        y_1_reg_756 <= y_fu_106;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_740 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln43_3_reg_766 <= add_ln43_3_fu_430_p2;
        or_ln43_reg_771 <= or_ln43_fu_436_p2;
        select_ln42_4_reg_761 <= select_ln42_4_fu_424_p3;
        select_ln43_2_reg_775 <= select_ln43_2_fu_459_p3;
        trunc_ln46_reg_779 <= trunc_ln46_fu_475_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln42_4_reg_761_pp0_iter4_reg == 1'd1) & (icmp_ln42_reg_740_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln43_4_reg_825 <= add_ln43_4_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln42_4_reg_761_pp0_iter4_reg == 1'd0) & (icmp_ln43_reg_744_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln43_reg_814 <= add_ln43_fu_536_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln42_reg_740 <= icmp_ln42_fu_350_p2;
        zext_ln42_cast_reg_729[31 : 0] <= zext_ln42_cast_fu_311_p1[31 : 0];
        zext_ln43_3_cast_reg_735[31 : 0] <= zext_ln43_3_cast_fu_315_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln42_fu_350_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln43_reg_744 <= icmp_ln43_fu_361_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_740_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln42_1_reg_819 <= grp_fu_738_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln42_4_reg_761_pp0_iter3_reg == 1'd1) & (icmp_ln42_reg_740_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln43_1_reg_809 <= grp_fu_734_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln42_4_reg_761_pp0_iter3_reg == 1'd0) & (icmp_ln43_reg_744_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln43_reg_804 <= grp_fu_420_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_740_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln42_1_reg_793 <= select_ln42_1_fu_513_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln42_reg_740_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sext_ln44_mid2_v_reg_830 <= {{add_ln43_6_fu_617_p2[63:2]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln42_fu_350_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln42_reg_740_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter14_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_reg_740_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_0_phi_fu_303_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_303_p4 = first_iter_0_reg_298;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_1_ce0 = 1'b1;
    end else begin
        filterCoeffs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln46_reg_779_pp0_iter14_reg == 2'd1) & (select_ln43_2_reg_775_pp0_iter14_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_1_we0 = 1'b1;
    end else begin
        filterCoeffs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_2_ce0 = 1'b1;
    end else begin
        filterCoeffs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln46_reg_779_pp0_iter14_reg == 2'd0) & ~(trunc_ln46_reg_779_pp0_iter14_reg == 2'd1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (select_ln43_2_reg_775_pp0_iter14_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_2_we0 = 1'b1;
    end else begin
        filterCoeffs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_3_ce0 = 1'b1;
    end else begin
        filterCoeffs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln46_reg_779_pp0_iter14_reg == 2'd0) & (select_ln43_2_reg_775_pp0_iter14_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_3_we0 = 1'b1;
    end else begin
        filterCoeffs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_4_ce0 = 1'b1;
    end else begin
        filterCoeffs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln46_reg_779_pp0_iter14_reg == 2'd1) & (select_ln43_2_reg_775_pp0_iter14_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_4_we0 = 1'b1;
    end else begin
        filterCoeffs_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_5_ce0 = 1'b1;
    end else begin
        filterCoeffs_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln46_reg_779_pp0_iter14_reg == 2'd0) & ~(trunc_ln46_reg_779_pp0_iter14_reg == 2'd1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (select_ln43_2_reg_775_pp0_iter14_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_5_we0 = 1'b1;
    end else begin
        filterCoeffs_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_6_ce0 = 1'b1;
    end else begin
        filterCoeffs_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln43_2_reg_775_pp0_iter14_reg == 2'd0) & ~(select_ln43_2_reg_775_pp0_iter14_reg == 2'd1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln46_reg_779_pp0_iter14_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_6_we0 = 1'b1;
    end else begin
        filterCoeffs_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_7_ce0 = 1'b1;
    end else begin
        filterCoeffs_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln43_2_reg_775_pp0_iter14_reg == 2'd0) & ~(select_ln43_2_reg_775_pp0_iter14_reg == 2'd1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln46_reg_779_pp0_iter14_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_7_we0 = 1'b1;
    end else begin
        filterCoeffs_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_8_ce0 = 1'b1;
    end else begin
        filterCoeffs_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln43_2_reg_775_pp0_iter14_reg == 2'd0) & ~(trunc_ln46_reg_779_pp0_iter14_reg == 2'd0) & ~(trunc_ln46_reg_779_pp0_iter14_reg == 2'd1) & ~(select_ln43_2_reg_775_pp0_iter14_reg == 2'd1) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_8_we0 = 1'b1;
    end else begin
        filterCoeffs_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_ce0 = 1'b1;
    end else begin
        filterCoeffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln46_reg_779_pp0_iter14_reg == 2'd0) & (select_ln43_2_reg_775_pp0_iter14_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_we0 = 1'b1;
    end else begin
        filterCoeffs_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln43_reg_771_pp0_iter6_reg == 1'd1))) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_498_ce = 1'b1;
    end else begin
        grp_fu_498_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_503_ce = 1'b1;
    end else begin
        grp_fu_503_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_520_ce = 1'b1;
    end else begin
        grp_fu_520_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_529_ce = 1'b1;
    end else begin
        grp_fu_529_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln43_reg_771_pp0_iter6_reg == 1'd1))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem1_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_1_fu_355_p2 = (indvar_flatten49_fu_118 + 96'd1);

assign add_ln42_fu_507_p0 = iChannel_fu_114;

assign add_ln42_fu_507_p2 = ($signed(add_ln42_fu_507_p0) + $signed(32'd1));

assign add_ln43_1_fu_555_p2 = (zext_ln43_2_fu_552_p1 + zext_ln43_fu_549_p1);

assign add_ln43_2_fu_573_p2 = (zext_ln43_3_cast_reg_735 + zext_ln42_3_fu_561_p1);

assign add_ln43_3_fu_430_p2 = (select_ln42_fu_400_p3 + 32'd1);

assign add_ln43_4_fu_544_p2 = (zext_ln42_cast_reg_729 + zext_ln43_5_fu_541_p1);

assign add_ln43_5_fu_585_p2 = (zext_ln43_6_fu_582_p1 + zext_ln42_2_fu_569_p1);

assign add_ln43_6_fu_617_p2 = (zext_ln43_7_fu_613_p1 + coeffs);

assign add_ln43_7_fu_366_p2 = (indvar_flatten_fu_110 + 64'd1);

assign add_ln43_fu_536_p2 = (zext_ln42_cast_reg_729 + zext_ln43_1_fu_533_p1);

assign add_ln44_fu_479_p2 = (select_ln43_fu_447_p3 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem1_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state15_pp0_stage0_iter14 = (m_axi_gmem1_RVALID == 1'b0);
end

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((or_ln43_reg_771_pp0_iter6_reg == 1'd1) & (m_axi_gmem1_ARREADY == 1'b0));
end

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_39_fu_455_p1 = add_ln43_3_fu_430_p2[1:0];

assign empty_fu_393_p0 = y_fu_106;

assign empty_fu_393_p1 = empty_fu_393_p0[1:0];

assign filterCoeffs_1_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_1_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_2_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_2_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_3_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_3_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_4_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_4_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_5_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_5_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_6_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_6_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_7_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_7_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_8_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_8_d0 = gmem1_addr_1_read_reg_845;

assign filterCoeffs_address0 = zext_ln42_1_fu_648_p1;

assign filterCoeffs_d0 = gmem1_addr_1_read_reg_845;

assign grp_fu_371_p_ce = grp_fu_498_ce;

assign grp_fu_371_p_din0 = iChannel_fu_114;

assign grp_fu_371_p_din1 = mul_ln39;

assign grp_fu_420_p_ce = grp_fu_503_ce;

assign grp_fu_420_p_din0 = y_1_reg_756;

assign grp_fu_420_p_din1 = convWidth;

assign grp_fu_734_p_ce = grp_fu_520_ce;

assign grp_fu_734_p_din0 = add_ln43_3_reg_766;

assign grp_fu_734_p_din1 = convWidth;

assign grp_fu_738_p_ce = grp_fu_529_ce;

assign grp_fu_738_p_din0 = add_ln42_reg_788;

assign grp_fu_738_p_din1 = mul_ln39;

assign icmp_ln42_fu_350_p2 = ((indvar_flatten49_fu_118 == mul_ln13_1) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_361_p2 = ((indvar_flatten_fu_110 == mul_ln13) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_419_p1 = convWidth;

assign icmp_ln44_fu_419_p2 = ((x_fu_102 == icmp_ln44_fu_419_p1) ? 1'b1 : 1'b0);

assign m_axi_gmem1_ARADDR = sext_ln43_fu_632_p1;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = convWidth;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 32'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 4'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign or_ln42_fu_407_p2 = (icmp_ln43_reg_744 | ap_phi_mux_first_iter_0_phi_fu_303_p4);

assign or_ln43_1_fu_442_p2 = (select_ln42_4_fu_424_p3 | icmp_ln43_reg_744);

assign or_ln43_fu_436_p2 = (select_ln42_4_fu_424_p3 | or_ln42_fu_407_p2);

assign select_ln42_1_fu_513_p2 = iChannel_fu_114;

assign select_ln42_1_fu_513_p3 = ((icmp_ln43_reg_744_pp0_iter2_reg[0:0] == 1'b1) ? add_ln42_fu_507_p2 : select_ln42_1_fu_513_p2);

assign select_ln42_2_fu_564_p3 = ((icmp_ln43_reg_744_pp0_iter5_reg[0:0] == 1'b1) ? mul_ln42_1_reg_819 : mul_ln42_reg_798_pp0_iter5_reg);

assign select_ln42_3_fu_412_p3 = ((icmp_ln43_reg_744[0:0] == 1'b1) ? 2'd0 : empty_fu_393_p1);

assign select_ln42_4_fu_424_p3 = ((icmp_ln43_reg_744[0:0] == 1'b1) ? icmp_ln44_1 : icmp_ln44_fu_419_p2);

assign select_ln42_5_fu_591_p3 = ((icmp_ln43_reg_744_pp0_iter5_reg[0:0] == 1'b1) ? zext_ln43_4_fu_578_p1 : add_ln43_1_fu_555_p2);

assign select_ln42_fu_400_p2 = y_fu_106;

assign select_ln42_fu_400_p3 = ((icmp_ln43_reg_744[0:0] == 1'b1) ? 32'd0 : select_ln42_fu_400_p2);

assign select_ln43_1_fu_598_p3 = ((select_ln42_4_reg_761_pp0_iter5_reg[0:0] == 1'b1) ? add_ln43_5_fu_585_p2 : select_ln42_5_fu_591_p3);

assign select_ln43_2_fu_459_p3 = ((select_ln42_4_fu_424_p3[0:0] == 1'b1) ? empty_39_fu_455_p1 : select_ln42_3_fu_412_p3);

assign select_ln43_3_fu_467_p3 = ((select_ln42_4_fu_424_p3[0:0] == 1'b1) ? add_ln43_3_fu_430_p2 : select_ln42_fu_400_p3);

assign select_ln43_4_fu_372_p3 = ((icmp_ln43_fu_361_p2[0:0] == 1'b1) ? 64'd1 : add_ln43_7_fu_366_p2);

assign select_ln43_fu_447_p3 = ((or_ln43_1_fu_442_p2[0:0] == 1'b1) ? 32'd0 : x_fu_102);

assign sext_ln43_fu_632_p1 = $signed(sext_ln44_mid2_v_reg_830);

assign sext_ln44_mid2_v_v_v_v_v_fu_605_p3 = {{select_ln43_1_fu_598_p3}, {2'd0}};

assign trunc_ln46_fu_475_p1 = select_ln43_fu_447_p3[1:0];

assign zext_ln42_1_fu_648_p1 = select_ln42_1_reg_793_pp0_iter14_reg;

assign zext_ln42_2_fu_569_p1 = select_ln42_2_fu_564_p3;

assign zext_ln42_3_fu_561_p1 = mul_ln42_1_reg_819;

assign zext_ln42_cast_fu_311_p1 = zext_ln42;

assign zext_ln43_1_fu_533_p1 = mul_ln43_reg_804;

assign zext_ln43_2_fu_552_p1 = add_ln43_reg_814;

assign zext_ln43_3_cast_fu_315_p1 = zext_ln43_3;

assign zext_ln43_4_fu_578_p1 = add_ln43_2_fu_573_p2;

assign zext_ln43_5_fu_541_p1 = mul_ln43_1_reg_809;

assign zext_ln43_6_fu_582_p1 = add_ln43_4_reg_825;

assign zext_ln43_7_fu_613_p1 = sext_ln44_mid2_v_v_v_v_v_fu_605_p3;

assign zext_ln43_fu_549_p1 = mul_ln42_reg_798_pp0_iter5_reg;

always @ (posedge ap_clk) begin
    zext_ln42_cast_reg_729[32] <= 1'b0;
    zext_ln43_3_cast_reg_735[32] <= 1'b0;
end

endmodule //Conv2D_HW_Conv2D_HW_Pipeline_loop_load_coef_x
