-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv2D_HW_Conv2D_HW_Pipeline_loop_load_coef_x is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_ln39 : IN STD_LOGIC_VECTOR (31 downto 0);
    convWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln42 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln13_1 : IN STD_LOGIC_VECTOR (95 downto 0);
    filterCoeffs_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_ce0 : OUT STD_LOGIC;
    filterCoeffs_we0 : OUT STD_LOGIC;
    filterCoeffs_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_8_ce0 : OUT STD_LOGIC;
    filterCoeffs_8_we0 : OUT STD_LOGIC;
    filterCoeffs_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_7_ce0 : OUT STD_LOGIC;
    filterCoeffs_7_we0 : OUT STD_LOGIC;
    filterCoeffs_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_6_ce0 : OUT STD_LOGIC;
    filterCoeffs_6_we0 : OUT STD_LOGIC;
    filterCoeffs_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_5_ce0 : OUT STD_LOGIC;
    filterCoeffs_5_we0 : OUT STD_LOGIC;
    filterCoeffs_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_4_ce0 : OUT STD_LOGIC;
    filterCoeffs_4_we0 : OUT STD_LOGIC;
    filterCoeffs_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_3_ce0 : OUT STD_LOGIC;
    filterCoeffs_3_we0 : OUT STD_LOGIC;
    filterCoeffs_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_2_ce0 : OUT STD_LOGIC;
    filterCoeffs_2_we0 : OUT STD_LOGIC;
    filterCoeffs_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    filterCoeffs_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    filterCoeffs_1_ce0 : OUT STD_LOGIC;
    filterCoeffs_1_we0 : OUT STD_LOGIC;
    filterCoeffs_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mul_ln13 : IN STD_LOGIC_VECTOR (63 downto 0);
    zext_ln43_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    icmp_ln44_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    coeffs : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_371_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_371_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_371_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_371_p_ce : OUT STD_LOGIC;
    grp_fu_420_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_420_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_420_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_420_p_ce : OUT STD_LOGIC;
    grp_fu_734_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_734_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_734_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_734_p_ce : OUT STD_LOGIC;
    grp_fu_738_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_738_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_738_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_738_p_ce : OUT STD_LOGIC );
end;


architecture behav of Conv2D_HW_Conv2D_HW_Pipeline_loop_load_coef_x is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal or_ln43_reg_771 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_reg_771_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_io : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln42_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal first_iter_0_reg_298 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln42_cast_fu_311_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln42_cast_reg_729 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln43_3_cast_fu_315_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln43_3_cast_reg_735 : STD_LOGIC_VECTOR (32 downto 0);
    signal icmp_ln42_reg_740 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_740_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_740_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_740_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_740_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_744 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_744_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_744_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_744_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_reg_744_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal y_1_reg_756 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_4_fu_424_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_4_reg_761 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_4_reg_761_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_4_reg_761_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_4_reg_761_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln43_3_fu_430_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_3_reg_766 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln43_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_reg_771_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_reg_771_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_reg_771_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_2_fu_459_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_2_reg_775_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_fu_475_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln46_reg_779_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln42_fu_507_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_reg_788 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_fu_513_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_reg_793_pp0_iter14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln42_reg_798 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln42_reg_798_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln43_reg_804 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln43_1_reg_809 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_fu_536_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln43_reg_814 : STD_LOGIC_VECTOR (32 downto 0);
    signal mul_ln42_1_reg_819 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_4_fu_544_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln43_4_reg_825 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln44_mid2_v_reg_830 : STD_LOGIC_VECTOR (61 downto 0);
    signal gmem1_addr_1_read_reg_845 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter6_stage0 : STD_LOGIC;
    signal ap_phi_mux_first_iter_0_phi_fu_303_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln42_1_fu_648_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln43_fu_632_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_fu_479_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln43_3_fu_467_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_110 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln43_4_fu_372_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal iChannel_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten49_fu_118 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln42_1_fu_355_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln43_7_fu_366_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_393_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_fu_400_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_393_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln44_fu_419_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln44_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln42_fu_400_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln42_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_1_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_39_fu_455_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln42_3_fu_412_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln43_fu_447_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln42_fu_507_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln42_1_fu_513_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln43_1_fu_533_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln43_5_fu_541_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln43_2_fu_552_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln43_fu_549_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln42_2_fu_564_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln42_3_fu_561_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln43_2_fu_573_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln43_6_fu_582_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln42_2_fu_569_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln43_4_fu_578_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln43_1_fu_555_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln43_5_fu_585_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln42_5_fu_591_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln43_1_fu_598_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln44_mid2_v_v_v_v_v_fu_605_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln43_7_fu_613_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln43_6_fu_617_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_498_ce : STD_LOGIC;
    signal grp_fu_503_ce : STD_LOGIC;
    signal grp_fu_520_ce : STD_LOGIC;
    signal grp_fu_529_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Conv2D_HW_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Conv2D_HW_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Conv2D_HW_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter6_stage0)) then 
                    ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_0_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_740_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_0_reg_298 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_0_reg_298 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    iChannel_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    iChannel_fu_114 <= ap_const_lv32_0;
                elsif (((icmp_ln42_reg_740_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    iChannel_fu_114 <= select_ln42_1_fu_513_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten49_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten49_fu_118 <= ap_const_lv96_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln42_fu_350_p2 = ap_const_lv1_0))) then 
                    indvar_flatten49_fu_118 <= add_ln42_1_fu_355_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_110 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln42_fu_350_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_110 <= select_ln43_4_fu_372_p3;
                end if;
            end if; 
        end if;
    end process;

    x_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_102 <= ap_const_lv32_0;
                elsif (((icmp_ln42_reg_740 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    x_fu_102 <= add_ln44_fu_479_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_106 <= ap_const_lv32_0;
                elsif (((icmp_ln42_reg_740 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    y_fu_106 <= select_ln43_3_fu_467_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln42_reg_788 <= add_ln42_fu_507_p2;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem1_addr_1_read_reg_845 <= m_axi_gmem1_RDATA;
                icmp_ln42_reg_740_pp0_iter2_reg <= icmp_ln42_reg_740;
                icmp_ln42_reg_740_pp0_iter3_reg <= icmp_ln42_reg_740_pp0_iter2_reg;
                icmp_ln42_reg_740_pp0_iter4_reg <= icmp_ln42_reg_740_pp0_iter3_reg;
                icmp_ln42_reg_740_pp0_iter5_reg <= icmp_ln42_reg_740_pp0_iter4_reg;
                icmp_ln43_reg_744_pp0_iter2_reg <= icmp_ln43_reg_744;
                icmp_ln43_reg_744_pp0_iter3_reg <= icmp_ln43_reg_744_pp0_iter2_reg;
                icmp_ln43_reg_744_pp0_iter4_reg <= icmp_ln43_reg_744_pp0_iter3_reg;
                icmp_ln43_reg_744_pp0_iter5_reg <= icmp_ln43_reg_744_pp0_iter4_reg;
                mul_ln42_reg_798 <= grp_fu_371_p_dout0;
                mul_ln42_reg_798_pp0_iter5_reg <= mul_ln42_reg_798;
                or_ln43_reg_771_pp0_iter3_reg <= or_ln43_reg_771;
                or_ln43_reg_771_pp0_iter4_reg <= or_ln43_reg_771_pp0_iter3_reg;
                or_ln43_reg_771_pp0_iter5_reg <= or_ln43_reg_771_pp0_iter4_reg;
                or_ln43_reg_771_pp0_iter6_reg <= or_ln43_reg_771_pp0_iter5_reg;
                select_ln42_1_reg_793_pp0_iter10_reg <= select_ln42_1_reg_793_pp0_iter9_reg;
                select_ln42_1_reg_793_pp0_iter11_reg <= select_ln42_1_reg_793_pp0_iter10_reg;
                select_ln42_1_reg_793_pp0_iter12_reg <= select_ln42_1_reg_793_pp0_iter11_reg;
                select_ln42_1_reg_793_pp0_iter13_reg <= select_ln42_1_reg_793_pp0_iter12_reg;
                select_ln42_1_reg_793_pp0_iter14_reg <= select_ln42_1_reg_793_pp0_iter13_reg;
                select_ln42_1_reg_793_pp0_iter4_reg <= select_ln42_1_reg_793;
                select_ln42_1_reg_793_pp0_iter5_reg <= select_ln42_1_reg_793_pp0_iter4_reg;
                select_ln42_1_reg_793_pp0_iter6_reg <= select_ln42_1_reg_793_pp0_iter5_reg;
                select_ln42_1_reg_793_pp0_iter7_reg <= select_ln42_1_reg_793_pp0_iter6_reg;
                select_ln42_1_reg_793_pp0_iter8_reg <= select_ln42_1_reg_793_pp0_iter7_reg;
                select_ln42_1_reg_793_pp0_iter9_reg <= select_ln42_1_reg_793_pp0_iter8_reg;
                select_ln42_4_reg_761_pp0_iter3_reg <= select_ln42_4_reg_761;
                select_ln42_4_reg_761_pp0_iter4_reg <= select_ln42_4_reg_761_pp0_iter3_reg;
                select_ln42_4_reg_761_pp0_iter5_reg <= select_ln42_4_reg_761_pp0_iter4_reg;
                select_ln43_2_reg_775_pp0_iter10_reg <= select_ln43_2_reg_775_pp0_iter9_reg;
                select_ln43_2_reg_775_pp0_iter11_reg <= select_ln43_2_reg_775_pp0_iter10_reg;
                select_ln43_2_reg_775_pp0_iter12_reg <= select_ln43_2_reg_775_pp0_iter11_reg;
                select_ln43_2_reg_775_pp0_iter13_reg <= select_ln43_2_reg_775_pp0_iter12_reg;
                select_ln43_2_reg_775_pp0_iter14_reg <= select_ln43_2_reg_775_pp0_iter13_reg;
                select_ln43_2_reg_775_pp0_iter3_reg <= select_ln43_2_reg_775;
                select_ln43_2_reg_775_pp0_iter4_reg <= select_ln43_2_reg_775_pp0_iter3_reg;
                select_ln43_2_reg_775_pp0_iter5_reg <= select_ln43_2_reg_775_pp0_iter4_reg;
                select_ln43_2_reg_775_pp0_iter6_reg <= select_ln43_2_reg_775_pp0_iter5_reg;
                select_ln43_2_reg_775_pp0_iter7_reg <= select_ln43_2_reg_775_pp0_iter6_reg;
                select_ln43_2_reg_775_pp0_iter8_reg <= select_ln43_2_reg_775_pp0_iter7_reg;
                select_ln43_2_reg_775_pp0_iter9_reg <= select_ln43_2_reg_775_pp0_iter8_reg;
                trunc_ln46_reg_779_pp0_iter10_reg <= trunc_ln46_reg_779_pp0_iter9_reg;
                trunc_ln46_reg_779_pp0_iter11_reg <= trunc_ln46_reg_779_pp0_iter10_reg;
                trunc_ln46_reg_779_pp0_iter12_reg <= trunc_ln46_reg_779_pp0_iter11_reg;
                trunc_ln46_reg_779_pp0_iter13_reg <= trunc_ln46_reg_779_pp0_iter12_reg;
                trunc_ln46_reg_779_pp0_iter14_reg <= trunc_ln46_reg_779_pp0_iter13_reg;
                trunc_ln46_reg_779_pp0_iter3_reg <= trunc_ln46_reg_779;
                trunc_ln46_reg_779_pp0_iter4_reg <= trunc_ln46_reg_779_pp0_iter3_reg;
                trunc_ln46_reg_779_pp0_iter5_reg <= trunc_ln46_reg_779_pp0_iter4_reg;
                trunc_ln46_reg_779_pp0_iter6_reg <= trunc_ln46_reg_779_pp0_iter5_reg;
                trunc_ln46_reg_779_pp0_iter7_reg <= trunc_ln46_reg_779_pp0_iter6_reg;
                trunc_ln46_reg_779_pp0_iter8_reg <= trunc_ln46_reg_779_pp0_iter7_reg;
                trunc_ln46_reg_779_pp0_iter9_reg <= trunc_ln46_reg_779_pp0_iter8_reg;
                y_1_reg_756 <= y_fu_106;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_740 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln43_3_reg_766 <= add_ln43_3_fu_430_p2;
                or_ln43_reg_771 <= or_ln43_fu_436_p2;
                select_ln42_4_reg_761 <= select_ln42_4_fu_424_p3;
                select_ln43_2_reg_775 <= select_ln43_2_fu_459_p3;
                trunc_ln46_reg_779 <= trunc_ln46_fu_475_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln42_4_reg_761_pp0_iter4_reg = ap_const_lv1_1) and (icmp_ln42_reg_740_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln43_4_reg_825 <= add_ln43_4_fu_544_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln42_4_reg_761_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln43_reg_744_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln43_reg_814 <= add_ln43_fu_536_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln42_reg_740 <= icmp_ln42_fu_350_p2;
                    zext_ln42_cast_reg_729(31 downto 0) <= zext_ln42_cast_fu_311_p1(31 downto 0);
                    zext_ln43_3_cast_reg_735(31 downto 0) <= zext_ln43_3_cast_fu_315_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln42_fu_350_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln43_reg_744 <= icmp_ln43_fu_361_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_740_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln42_1_reg_819 <= grp_fu_738_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln42_4_reg_761_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln42_reg_740_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln43_1_reg_809 <= grp_fu_734_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln42_4_reg_761_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln43_reg_744_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln43_reg_804 <= grp_fu_420_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_740_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln42_1_reg_793 <= select_ln42_1_fu_513_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln42_reg_740_pp0_iter5_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                sext_ln44_mid2_v_reg_830 <= add_ln43_6_fu_617_p2(63 downto 2);
            end if;
        end if;
    end process;
    zext_ln42_cast_reg_729(32) <= '0';
    zext_ln43_3_cast_reg_735(32) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln42_1_fu_355_p2 <= std_logic_vector(unsigned(indvar_flatten49_fu_118) + unsigned(ap_const_lv96_1));
    add_ln42_fu_507_p0 <= iChannel_fu_114;
    add_ln42_fu_507_p2 <= std_logic_vector(signed(add_ln42_fu_507_p0) + signed(ap_const_lv32_1));
    add_ln43_1_fu_555_p2 <= std_logic_vector(unsigned(zext_ln43_2_fu_552_p1) + unsigned(zext_ln43_fu_549_p1));
    add_ln43_2_fu_573_p2 <= std_logic_vector(unsigned(zext_ln43_3_cast_reg_735) + unsigned(zext_ln42_3_fu_561_p1));
    add_ln43_3_fu_430_p2 <= std_logic_vector(unsigned(select_ln42_fu_400_p3) + unsigned(ap_const_lv32_1));
    add_ln43_4_fu_544_p2 <= std_logic_vector(unsigned(zext_ln42_cast_reg_729) + unsigned(zext_ln43_5_fu_541_p1));
    add_ln43_5_fu_585_p2 <= std_logic_vector(unsigned(zext_ln43_6_fu_582_p1) + unsigned(zext_ln42_2_fu_569_p1));
    add_ln43_6_fu_617_p2 <= std_logic_vector(unsigned(zext_ln43_7_fu_613_p1) + unsigned(coeffs));
    add_ln43_7_fu_366_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_110) + unsigned(ap_const_lv64_1));
    add_ln43_fu_536_p2 <= std_logic_vector(unsigned(zext_ln42_cast_reg_729) + unsigned(zext_ln43_1_fu_533_p1));
    add_ln44_fu_479_p2 <= std_logic_vector(unsigned(select_ln43_fu_447_p3) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter14, m_axi_gmem1_RVALID, ap_block_state8_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (m_axi_gmem1_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter14, m_axi_gmem1_RVALID, ap_block_state8_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (m_axi_gmem1_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_io)));
    end process;

        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state15_pp0_stage0_iter14_assign_proc : process(m_axi_gmem1_RVALID)
    begin
                ap_block_state15_pp0_stage0_iter14 <= (m_axi_gmem1_RVALID = ap_const_logic_0);
    end process;

        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_io_assign_proc : process(m_axi_gmem1_ARREADY, or_ln43_reg_771_pp0_iter6_reg)
    begin
                ap_block_state8_io <= ((or_ln43_reg_771_pp0_iter6_reg = ap_const_lv1_1) and (m_axi_gmem1_ARREADY = ap_const_logic_0));
    end process;

        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln42_fu_350_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln42_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter6_stage0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone, icmp_ln42_reg_740_pp0_iter5_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln42_reg_740_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter6_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter6_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter14_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter14_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_0_phi_fu_303_p4_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0, first_iter_0_reg_298, icmp_ln42_reg_740_pp0_iter2_reg)
    begin
        if (((icmp_ln42_reg_740_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_0_phi_fu_303_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_0_phi_fu_303_p4 <= first_iter_0_reg_298;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_39_fu_455_p1 <= add_ln43_3_fu_430_p2(2 - 1 downto 0);
    empty_fu_393_p0 <= y_fu_106;
    empty_fu_393_p1 <= empty_fu_393_p0(2 - 1 downto 0);
    filterCoeffs_1_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_1_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_1_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_1_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_1) and (select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_1_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_2_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_2_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_2_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_2_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if ((not((trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_0)) and not((trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_2_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_3_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_3_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_3_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_3_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_0) and (select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_3_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_4_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_4_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_4_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_4_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_1) and (select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_4_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_5_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_5_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_5_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_5_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if ((not((trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_0)) and not((trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_5_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_6_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_6_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_6_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_6_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if ((not((select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_0)) and not((select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_6_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_7_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_7_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_7_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_7_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if ((not((select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_0)) and not((select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_7_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_8_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_8_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_8_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_8_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if ((not((select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_0)) and not((trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_0)) and not((trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_1)) and not((select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_8_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_address0 <= zext_ln42_1_fu_648_p1(8 - 1 downto 0);

    filterCoeffs_ce0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_ce0 <= ap_const_logic_1;
        else 
            filterCoeffs_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    filterCoeffs_d0 <= gmem1_addr_1_read_reg_845;

    filterCoeffs_we0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001, select_ln43_2_reg_775_pp0_iter14_reg, trunc_ln46_reg_779_pp0_iter14_reg)
    begin
        if (((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and (trunc_ln46_reg_779_pp0_iter14_reg = ap_const_lv2_0) and (select_ln43_2_reg_775_pp0_iter14_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            filterCoeffs_we0 <= ap_const_logic_1;
        else 
            filterCoeffs_we0 <= ap_const_logic_0;
        end if; 
    end process;


    gmem1_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_gmem1_ARREADY, or_ln43_reg_771_pp0_iter6_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln43_reg_771_pp0_iter6_reg = ap_const_lv1_1))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter14, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_371_p_ce <= grp_fu_498_ce;
    grp_fu_371_p_din0 <= iChannel_fu_114;
    grp_fu_371_p_din1 <= mul_ln39;
    grp_fu_420_p_ce <= grp_fu_503_ce;
    grp_fu_420_p_din0 <= y_1_reg_756;
    grp_fu_420_p_din1 <= convWidth;

    grp_fu_498_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_498_ce <= ap_const_logic_1;
        else 
            grp_fu_498_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_503_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_503_ce <= ap_const_logic_1;
        else 
            grp_fu_503_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_520_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_520_ce <= ap_const_logic_1;
        else 
            grp_fu_520_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_529_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_529_ce <= ap_const_logic_1;
        else 
            grp_fu_529_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_734_p_ce <= grp_fu_520_ce;
    grp_fu_734_p_din0 <= add_ln43_3_reg_766;
    grp_fu_734_p_din1 <= convWidth;
    grp_fu_738_p_ce <= grp_fu_529_ce;
    grp_fu_738_p_din0 <= add_ln42_reg_788;
    grp_fu_738_p_din1 <= mul_ln39;
    icmp_ln42_fu_350_p2 <= "1" when (indvar_flatten49_fu_118 = mul_ln13_1) else "0";
    icmp_ln43_fu_361_p2 <= "1" when (indvar_flatten_fu_110 = mul_ln13) else "0";
    icmp_ln44_fu_419_p1 <= convWidth;
    icmp_ln44_fu_419_p2 <= "1" when (x_fu_102 = icmp_ln44_fu_419_p1) else "0";
    m_axi_gmem1_ARADDR <= sext_ln43_fu_632_p1;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= convWidth;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter7, or_ln43_reg_771_pp0_iter6_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln43_reg_771_pp0_iter6_reg = ap_const_lv1_1))) then 
            m_axi_gmem1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    or_ln42_fu_407_p2 <= (icmp_ln43_reg_744 or ap_phi_mux_first_iter_0_phi_fu_303_p4);
    or_ln43_1_fu_442_p2 <= (select_ln42_4_fu_424_p3 or icmp_ln43_reg_744);
    or_ln43_fu_436_p2 <= (select_ln42_4_fu_424_p3 or or_ln42_fu_407_p2);
    select_ln42_1_fu_513_p2 <= iChannel_fu_114;
    select_ln42_1_fu_513_p3 <= 
        add_ln42_fu_507_p2 when (icmp_ln43_reg_744_pp0_iter2_reg(0) = '1') else 
        select_ln42_1_fu_513_p2;
    select_ln42_2_fu_564_p3 <= 
        mul_ln42_1_reg_819 when (icmp_ln43_reg_744_pp0_iter5_reg(0) = '1') else 
        mul_ln42_reg_798_pp0_iter5_reg;
    select_ln42_3_fu_412_p3 <= 
        ap_const_lv2_0 when (icmp_ln43_reg_744(0) = '1') else 
        empty_fu_393_p1;
    select_ln42_4_fu_424_p3 <= 
        icmp_ln44_1 when (icmp_ln43_reg_744(0) = '1') else 
        icmp_ln44_fu_419_p2;
    select_ln42_5_fu_591_p3 <= 
        zext_ln43_4_fu_578_p1 when (icmp_ln43_reg_744_pp0_iter5_reg(0) = '1') else 
        add_ln43_1_fu_555_p2;
    select_ln42_fu_400_p2 <= y_fu_106;
    select_ln42_fu_400_p3 <= 
        ap_const_lv32_0 when (icmp_ln43_reg_744(0) = '1') else 
        select_ln42_fu_400_p2;
    select_ln43_1_fu_598_p3 <= 
        add_ln43_5_fu_585_p2 when (select_ln42_4_reg_761_pp0_iter5_reg(0) = '1') else 
        select_ln42_5_fu_591_p3;
    select_ln43_2_fu_459_p3 <= 
        empty_39_fu_455_p1 when (select_ln42_4_fu_424_p3(0) = '1') else 
        select_ln42_3_fu_412_p3;
    select_ln43_3_fu_467_p3 <= 
        add_ln43_3_fu_430_p2 when (select_ln42_4_fu_424_p3(0) = '1') else 
        select_ln42_fu_400_p3;
    select_ln43_4_fu_372_p3 <= 
        ap_const_lv64_1 when (icmp_ln43_fu_361_p2(0) = '1') else 
        add_ln43_7_fu_366_p2;
    select_ln43_fu_447_p3 <= 
        ap_const_lv32_0 when (or_ln43_1_fu_442_p2(0) = '1') else 
        x_fu_102;
        sext_ln43_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_mid2_v_reg_830),64));

    sext_ln44_mid2_v_v_v_v_v_fu_605_p3 <= (select_ln43_1_fu_598_p3 & ap_const_lv2_0);
    trunc_ln46_fu_475_p1 <= select_ln43_fu_447_p3(2 - 1 downto 0);
    zext_ln42_1_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln42_1_reg_793_pp0_iter14_reg),64));
    zext_ln42_2_fu_569_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln42_2_fu_564_p3),34));
    zext_ln42_3_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln42_1_reg_819),33));
    zext_ln42_cast_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln42),33));
    zext_ln43_1_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln43_reg_804),33));
    zext_ln43_2_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_reg_814),34));
    zext_ln43_3_cast_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln43_3),33));
    zext_ln43_4_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_2_fu_573_p2),34));
    zext_ln43_5_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln43_1_reg_809),33));
    zext_ln43_6_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_4_reg_825),34));
    zext_ln43_7_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln44_mid2_v_v_v_v_v_fu_605_p3),64));
    zext_ln43_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln42_reg_798_pp0_iter5_reg),34));
end behav;
