// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv2D_HW_Conv2D_HW_Pipeline_loop_acc_x (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        inputWidth,
        inputHeight,
        y,
        mul_ln13_1,
        convWidth,
        mul_ln13,
        p_cast10_mid1117,
        icmp_ln44_1,
        zext_ln60,
        input_r,
        filterCoeffs_address0,
        filterCoeffs_ce0,
        filterCoeffs_q0,
        filterCoeffs_1_address0,
        filterCoeffs_1_ce0,
        filterCoeffs_1_q0,
        filterCoeffs_2_address0,
        filterCoeffs_2_ce0,
        filterCoeffs_2_q0,
        filterCoeffs_3_address0,
        filterCoeffs_3_ce0,
        filterCoeffs_3_q0,
        filterCoeffs_4_address0,
        filterCoeffs_4_ce0,
        filterCoeffs_4_q0,
        filterCoeffs_5_address0,
        filterCoeffs_5_ce0,
        filterCoeffs_5_q0,
        filterCoeffs_6_address0,
        filterCoeffs_6_ce0,
        filterCoeffs_6_q0,
        filterCoeffs_7_address0,
        filterCoeffs_7_ce0,
        filterCoeffs_7_q0,
        filterCoeffs_8_address0,
        filterCoeffs_8_ce0,
        filterCoeffs_8_q0,
        acc_out,
        acc_out_ap_vld,
        grp_fu_371_p_din0,
        grp_fu_371_p_din1,
        grp_fu_371_p_dout0,
        grp_fu_371_p_ce,
        grp_fu_420_p_din0,
        grp_fu_420_p_din1,
        grp_fu_420_p_dout0,
        grp_fu_420_p_ce,
        grp_fu_734_p_din0,
        grp_fu_734_p_din1,
        grp_fu_734_p_dout0,
        grp_fu_734_p_ce,
        grp_fu_738_p_din0,
        grp_fu_738_p_din1,
        grp_fu_738_p_dout0,
        grp_fu_738_p_ce,
        grp_fu_425_p_din0,
        grp_fu_425_p_din1,
        grp_fu_425_p_dout0,
        grp_fu_425_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [31:0] inputWidth;
input  [31:0] inputHeight;
input  [31:0] y;
input  [95:0] mul_ln13_1;
input  [31:0] convWidth;
input  [63:0] mul_ln13;
input  [31:0] p_cast10_mid1117;
input  [0:0] icmp_ln44_1;
input  [31:0] zext_ln60;
input  [63:0] input_r;
output  [7:0] filterCoeffs_address0;
output   filterCoeffs_ce0;
input  [31:0] filterCoeffs_q0;
output  [7:0] filterCoeffs_1_address0;
output   filterCoeffs_1_ce0;
input  [31:0] filterCoeffs_1_q0;
output  [7:0] filterCoeffs_2_address0;
output   filterCoeffs_2_ce0;
input  [31:0] filterCoeffs_2_q0;
output  [7:0] filterCoeffs_3_address0;
output   filterCoeffs_3_ce0;
input  [31:0] filterCoeffs_3_q0;
output  [7:0] filterCoeffs_4_address0;
output   filterCoeffs_4_ce0;
input  [31:0] filterCoeffs_4_q0;
output  [7:0] filterCoeffs_5_address0;
output   filterCoeffs_5_ce0;
input  [31:0] filterCoeffs_5_q0;
output  [7:0] filterCoeffs_6_address0;
output   filterCoeffs_6_ce0;
input  [31:0] filterCoeffs_6_q0;
output  [7:0] filterCoeffs_7_address0;
output   filterCoeffs_7_ce0;
input  [31:0] filterCoeffs_7_q0;
output  [7:0] filterCoeffs_8_address0;
output   filterCoeffs_8_ce0;
input  [31:0] filterCoeffs_8_q0;
output  [31:0] acc_out;
output   acc_out_ap_vld;
output  [31:0] grp_fu_371_p_din0;
output  [31:0] grp_fu_371_p_din1;
input  [31:0] grp_fu_371_p_dout0;
output   grp_fu_371_p_ce;
output  [31:0] grp_fu_420_p_din0;
output  [31:0] grp_fu_420_p_din1;
input  [31:0] grp_fu_420_p_dout0;
output   grp_fu_420_p_ce;
output  [31:0] grp_fu_734_p_din0;
output  [31:0] grp_fu_734_p_din1;
input  [31:0] grp_fu_734_p_dout0;
output   grp_fu_734_p_ce;
output  [31:0] grp_fu_738_p_din0;
output  [31:0] grp_fu_738_p_din1;
input  [31:0] grp_fu_738_p_dout0;
output   grp_fu_738_p_ce;
output  [31:0] grp_fu_425_p_din0;
output  [31:0] grp_fu_425_p_din1;
input  [31:0] grp_fu_425_p_dout0;
output   grp_fu_425_p_ce;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg filterCoeffs_ce0;
reg filterCoeffs_1_ce0;
reg filterCoeffs_2_ce0;
reg filterCoeffs_3_ce0;
reg filterCoeffs_4_ce0;
reg filterCoeffs_5_ce0;
reg filterCoeffs_6_ce0;
reg filterCoeffs_7_ce0;
reg filterCoeffs_8_ce0;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg   [0:0] or_ln58_reg_940;
reg   [0:0] or_ln58_reg_940_pp0_iter7_reg;
reg    ap_block_state9_io;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
reg   [0:0] icmp_ln60_reg_900;
reg   [0:0] icmp_ln60_reg_900_pp0_iter14_reg;
reg    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_401_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_AR;
reg   [0:0] first_iter_1_reg_335;
reg    ap_block_pp0_stage0_11001;
wire   [33:0] zext_ln60_cast_fu_348_p1;
reg   [33:0] zext_ln60_cast_reg_880;
wire   [32:0] p_cast10_mid1117_cast_fu_352_p1;
reg   [32:0] p_cast10_mid1117_cast_reg_885;
reg  signed [31:0] iChannel_reg_890;
wire  signed [31:0] add_ln60_fu_395_p2;
reg  signed [31:0] add_ln60_reg_895;
reg   [0:0] icmp_ln60_reg_900_pp0_iter2_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter3_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter4_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter5_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter6_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter7_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter8_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter9_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter10_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter11_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter12_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter13_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter15_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter16_reg;
reg   [0:0] icmp_ln60_reg_900_pp0_iter17_reg;
wire   [0:0] icmp_ln61_fu_412_p2;
reg   [0:0] icmp_ln61_reg_904;
reg   [0:0] icmp_ln61_reg_904_pp0_iter2_reg;
reg   [0:0] icmp_ln61_reg_904_pp0_iter3_reg;
reg   [0:0] icmp_ln61_reg_904_pp0_iter4_reg;
reg   [0:0] icmp_ln61_reg_904_pp0_iter5_reg;
wire   [31:0] select_ln60_1_fu_417_p3;
reg   [31:0] select_ln60_1_reg_915;
reg   [31:0] select_ln60_1_reg_915_pp0_iter2_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter3_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter4_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter5_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter6_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter7_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter8_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter9_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter10_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter11_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter12_reg;
reg   [31:0] select_ln60_1_reg_915_pp0_iter13_reg;
reg  signed [31:0] tmp4_reg_920;
wire  signed [31:0] empty_40_fu_465_p2;
reg  signed [31:0] empty_40_reg_925;
reg  signed [31:0] tmp4_mid1_reg_930;
wire   [0:0] select_ln60_5_fu_501_p3;
reg   [0:0] select_ln60_5_reg_935;
reg   [0:0] select_ln60_5_reg_935_pp0_iter4_reg;
reg   [0:0] select_ln60_5_reg_935_pp0_iter5_reg;
wire   [0:0] or_ln58_fu_513_p2;
reg   [0:0] or_ln58_reg_940_pp0_iter4_reg;
reg   [0:0] or_ln58_reg_940_pp0_iter5_reg;
reg   [0:0] or_ln58_reg_940_pp0_iter6_reg;
wire  signed [31:0] p_mid1_fu_532_p2;
reg  signed [31:0] p_mid1_reg_944;
wire   [1:0] select_ln58_2_fu_541_p3;
reg   [1:0] select_ln58_2_reg_949;
reg   [1:0] select_ln58_2_reg_949_pp0_iter4_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter5_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter6_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter7_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter8_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter9_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter10_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter11_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter12_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter13_reg;
reg   [1:0] select_ln58_2_reg_949_pp0_iter14_reg;
wire   [1:0] trunc_ln65_fu_557_p1;
reg   [1:0] trunc_ln65_reg_954;
reg   [1:0] trunc_ln65_reg_954_pp0_iter4_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter5_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter6_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter7_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter8_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter9_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter10_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter11_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter12_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter13_reg;
reg   [1:0] trunc_ln65_reg_954_pp0_iter14_reg;
reg   [31:0] empty_reg_961;
reg   [31:0] empty_41_reg_967;
reg   [31:0] p_mid1111_reg_972;
wire   [31:0] grp_fu_589_p2;
reg   [31:0] p_mid162_reg_978;
wire   [33:0] add_ln58_fu_649_p2;
reg   [33:0] add_ln58_reg_983;
reg   [61:0] sext_ln62_mid2_v_reg_988;
wire   [31:0] coeffValue_fu_741_p5;
reg  signed [31:0] coeffValue_reg_1048;
reg  signed [31:0] pixelValue_reg_1053;
reg   [31:0] trunc_ln3_reg_1068;
reg    ap_condition_exit_pp0_iter6_stage0;
reg   [0:0] ap_phi_mux_first_iter_1_phi_fu_340_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln58_2_fu_696_p1;
wire  signed [63:0] sext_ln58_fu_680_p1;
reg   [31:0] acc_fu_116;
wire   [31:0] acc_1_fu_777_p2;
reg   [31:0] cx_fu_120;
wire   [31:0] add_ln62_fu_561_p2;
reg   [31:0] cy_fu_124;
wire   [31:0] select_ln61_fu_549_p3;
reg   [63:0] indvar_flatten70_fu_128;
wire   [63:0] select_ln61_1_fu_431_p3;
reg   [31:0] iChannel_1_fu_132;
reg   [95:0] indvar_flatten161_fu_136;
wire   [95:0] add_ln60_1_fu_406_p2;
reg    ap_block_pp0_stage0_01001;
wire  signed [31:0] add_ln60_fu_395_p0;
wire  signed [31:0] select_ln60_1_fu_417_p2;
wire   [63:0] add_ln61_1_fu_425_p2;
wire   [1:0] empty_42_fu_470_p1;
wire   [0:0] icmp_ln62_fu_496_p2;
wire   [31:0] select_ln60_fu_477_p3;
wire   [0:0] or_ln60_fu_484_p2;
wire   [0:0] or_ln58_1_fu_519_p2;
wire   [31:0] add_ln61_fu_507_p2;
wire   [1:0] empty_44_fu_537_p1;
wire   [1:0] select_ln60_4_fu_489_p3;
wire   [31:0] select_ln58_fu_524_p3;
wire   [32:0] zext_ln61_fu_593_p1;
wire   [32:0] p_cast10_fu_596_p1;
wire   [31:0] select_ln60_2_fu_608_p3;
wire   [32:0] zext_ln61_1_fu_605_p1;
wire   [32:0] tmp5_mid1119_fu_617_p2;
wire   [32:0] tmp5_fu_599_p2;
wire   [32:0] zext_ln60_1_fu_613_p1;
wire   [32:0] p_cast10_mid1_fu_629_p1;
wire   [32:0] tmp5_mid1_fu_632_p2;
wire   [32:0] select_ln60_3_fu_622_p3;
wire   [32:0] select_ln58_1_fu_638_p3;
wire   [33:0] zext_ln58_fu_645_p1;
wire   [35:0] sext_ln62_mid2_v_v_v_v_v_fu_654_p3;
wire   [63:0] zext_ln58_1_fu_661_p1;
wire   [63:0] add_ln58_1_fu_665_p2;
wire   [31:0] tmp_fu_708_p5;
wire   [31:0] tmp_1_fu_719_p5;
wire   [31:0] tmp_2_fu_730_p5;
wire   [51:0] grp_fu_758_p2;
reg    grp_fu_454_ce;
reg    grp_fu_458_ce;
reg    grp_fu_577_ce;
reg    grp_fu_581_ce;
reg    grp_fu_585_ce;
reg    grp_fu_589_ce;
reg    grp_fu_758_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_done_reg = 1'b0;
end

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_mid1_reg_944),
    .din1(inputWidth),
    .ce(grp_fu_589_ce),
    .dout(grp_fu_589_p2)
);

Conv2D_HW_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U29(
    .din0(filterCoeffs_q0),
    .din1(filterCoeffs_1_q0),
    .din2(filterCoeffs_2_q0),
    .din3(trunc_ln65_reg_954_pp0_iter14_reg),
    .dout(tmp_fu_708_p5)
);

Conv2D_HW_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U30(
    .din0(filterCoeffs_3_q0),
    .din1(filterCoeffs_4_q0),
    .din2(filterCoeffs_5_q0),
    .din3(trunc_ln65_reg_954_pp0_iter14_reg),
    .dout(tmp_1_fu_719_p5)
);

Conv2D_HW_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U31(
    .din0(filterCoeffs_6_q0),
    .din1(filterCoeffs_7_q0),
    .din2(filterCoeffs_8_q0),
    .din3(trunc_ln65_reg_954_pp0_iter14_reg),
    .dout(tmp_2_fu_730_p5)
);

Conv2D_HW_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U32(
    .din0(tmp_fu_708_p5),
    .din1(tmp_1_fu_719_p5),
    .din2(tmp_2_fu_730_p5),
    .din3(select_ln58_2_reg_949_pp0_iter14_reg),
    .dout(coeffValue_fu_741_p5)
);

Conv2D_HW_mul_32s_32s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 52 ))
mul_32s_32s_52_2_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pixelValue_reg_1053),
    .din1(coeffValue_reg_1048),
    .ce(grp_fu_758_ce),
    .dout(grp_fu_758_p2)
);

Conv2D_HW_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter6_stage0)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_116 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter18 == 1'b1) & (icmp_ln60_reg_900_pp0_iter17_reg == 1'd0))) begin
            acc_fu_116 <= acc_1_fu_777_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cx_fu_120 <= 32'd0;
        end else if (((icmp_ln60_reg_900_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            cx_fu_120 <= add_ln62_fu_561_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            cy_fu_124 <= 32'd0;
        end else if (((icmp_ln60_reg_900_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            cy_fu_124 <= select_ln61_fu_549_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_reg_900_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_1_reg_335 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_1_reg_335 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            iChannel_1_fu_132 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln60_fu_401_p2 == 1'd0))) begin
            iChannel_1_fu_132 <= select_ln60_1_fu_417_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten161_fu_136 <= 96'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln60_fu_401_p2 == 1'd0))) begin
            indvar_flatten161_fu_136 <= add_ln60_1_fu_406_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten70_fu_128 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln60_fu_401_p2 == 1'd0))) begin
            indvar_flatten70_fu_128 <= select_ln61_1_fu_431_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_reg_900_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln58_reg_983 <= add_ln58_fu_649_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln60_reg_895 <= add_ln60_fu_395_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        iChannel_reg_890 <= iChannel_1_fu_132;
        icmp_ln60_reg_900 <= icmp_ln60_fu_401_p2;
        p_cast10_mid1117_cast_reg_885[31 : 0] <= p_cast10_mid1117_cast_fu_352_p1[31 : 0];
        zext_ln60_cast_reg_880[31 : 0] <= zext_ln60_cast_fu_348_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        empty_reg_961 <= grp_fu_734_p_dout0;
        icmp_ln60_reg_900_pp0_iter10_reg <= icmp_ln60_reg_900_pp0_iter9_reg;
        icmp_ln60_reg_900_pp0_iter11_reg <= icmp_ln60_reg_900_pp0_iter10_reg;
        icmp_ln60_reg_900_pp0_iter12_reg <= icmp_ln60_reg_900_pp0_iter11_reg;
        icmp_ln60_reg_900_pp0_iter13_reg <= icmp_ln60_reg_900_pp0_iter12_reg;
        icmp_ln60_reg_900_pp0_iter14_reg <= icmp_ln60_reg_900_pp0_iter13_reg;
        icmp_ln60_reg_900_pp0_iter15_reg <= icmp_ln60_reg_900_pp0_iter14_reg;
        icmp_ln60_reg_900_pp0_iter16_reg <= icmp_ln60_reg_900_pp0_iter15_reg;
        icmp_ln60_reg_900_pp0_iter17_reg <= icmp_ln60_reg_900_pp0_iter16_reg;
        icmp_ln60_reg_900_pp0_iter2_reg <= icmp_ln60_reg_900;
        icmp_ln60_reg_900_pp0_iter3_reg <= icmp_ln60_reg_900_pp0_iter2_reg;
        icmp_ln60_reg_900_pp0_iter4_reg <= icmp_ln60_reg_900_pp0_iter3_reg;
        icmp_ln60_reg_900_pp0_iter5_reg <= icmp_ln60_reg_900_pp0_iter4_reg;
        icmp_ln60_reg_900_pp0_iter6_reg <= icmp_ln60_reg_900_pp0_iter5_reg;
        icmp_ln60_reg_900_pp0_iter7_reg <= icmp_ln60_reg_900_pp0_iter6_reg;
        icmp_ln60_reg_900_pp0_iter8_reg <= icmp_ln60_reg_900_pp0_iter7_reg;
        icmp_ln60_reg_900_pp0_iter9_reg <= icmp_ln60_reg_900_pp0_iter8_reg;
        icmp_ln61_reg_904_pp0_iter2_reg <= icmp_ln61_reg_904;
        icmp_ln61_reg_904_pp0_iter3_reg <= icmp_ln61_reg_904_pp0_iter2_reg;
        icmp_ln61_reg_904_pp0_iter4_reg <= icmp_ln61_reg_904_pp0_iter3_reg;
        icmp_ln61_reg_904_pp0_iter5_reg <= icmp_ln61_reg_904_pp0_iter4_reg;
        or_ln58_reg_940_pp0_iter4_reg <= or_ln58_reg_940;
        or_ln58_reg_940_pp0_iter5_reg <= or_ln58_reg_940_pp0_iter4_reg;
        or_ln58_reg_940_pp0_iter6_reg <= or_ln58_reg_940_pp0_iter5_reg;
        or_ln58_reg_940_pp0_iter7_reg <= or_ln58_reg_940_pp0_iter6_reg;
        select_ln58_2_reg_949_pp0_iter10_reg <= select_ln58_2_reg_949_pp0_iter9_reg;
        select_ln58_2_reg_949_pp0_iter11_reg <= select_ln58_2_reg_949_pp0_iter10_reg;
        select_ln58_2_reg_949_pp0_iter12_reg <= select_ln58_2_reg_949_pp0_iter11_reg;
        select_ln58_2_reg_949_pp0_iter13_reg <= select_ln58_2_reg_949_pp0_iter12_reg;
        select_ln58_2_reg_949_pp0_iter14_reg <= select_ln58_2_reg_949_pp0_iter13_reg;
        select_ln58_2_reg_949_pp0_iter4_reg <= select_ln58_2_reg_949;
        select_ln58_2_reg_949_pp0_iter5_reg <= select_ln58_2_reg_949_pp0_iter4_reg;
        select_ln58_2_reg_949_pp0_iter6_reg <= select_ln58_2_reg_949_pp0_iter5_reg;
        select_ln58_2_reg_949_pp0_iter7_reg <= select_ln58_2_reg_949_pp0_iter6_reg;
        select_ln58_2_reg_949_pp0_iter8_reg <= select_ln58_2_reg_949_pp0_iter7_reg;
        select_ln58_2_reg_949_pp0_iter9_reg <= select_ln58_2_reg_949_pp0_iter8_reg;
        select_ln60_1_reg_915_pp0_iter10_reg <= select_ln60_1_reg_915_pp0_iter9_reg;
        select_ln60_1_reg_915_pp0_iter11_reg <= select_ln60_1_reg_915_pp0_iter10_reg;
        select_ln60_1_reg_915_pp0_iter12_reg <= select_ln60_1_reg_915_pp0_iter11_reg;
        select_ln60_1_reg_915_pp0_iter13_reg <= select_ln60_1_reg_915_pp0_iter12_reg;
        select_ln60_1_reg_915_pp0_iter2_reg <= select_ln60_1_reg_915;
        select_ln60_1_reg_915_pp0_iter3_reg <= select_ln60_1_reg_915_pp0_iter2_reg;
        select_ln60_1_reg_915_pp0_iter4_reg <= select_ln60_1_reg_915_pp0_iter3_reg;
        select_ln60_1_reg_915_pp0_iter5_reg <= select_ln60_1_reg_915_pp0_iter4_reg;
        select_ln60_1_reg_915_pp0_iter6_reg <= select_ln60_1_reg_915_pp0_iter5_reg;
        select_ln60_1_reg_915_pp0_iter7_reg <= select_ln60_1_reg_915_pp0_iter6_reg;
        select_ln60_1_reg_915_pp0_iter8_reg <= select_ln60_1_reg_915_pp0_iter7_reg;
        select_ln60_1_reg_915_pp0_iter9_reg <= select_ln60_1_reg_915_pp0_iter8_reg;
        select_ln60_5_reg_935_pp0_iter4_reg <= select_ln60_5_reg_935;
        select_ln60_5_reg_935_pp0_iter5_reg <= select_ln60_5_reg_935_pp0_iter4_reg;
        sext_ln62_mid2_v_reg_988 <= {{add_ln58_1_fu_665_p2[63:2]}};
        tmp4_reg_920 <= grp_fu_371_p_dout0;
        trunc_ln65_reg_954_pp0_iter10_reg <= trunc_ln65_reg_954_pp0_iter9_reg;
        trunc_ln65_reg_954_pp0_iter11_reg <= trunc_ln65_reg_954_pp0_iter10_reg;
        trunc_ln65_reg_954_pp0_iter12_reg <= trunc_ln65_reg_954_pp0_iter11_reg;
        trunc_ln65_reg_954_pp0_iter13_reg <= trunc_ln65_reg_954_pp0_iter12_reg;
        trunc_ln65_reg_954_pp0_iter14_reg <= trunc_ln65_reg_954_pp0_iter13_reg;
        trunc_ln65_reg_954_pp0_iter4_reg <= trunc_ln65_reg_954;
        trunc_ln65_reg_954_pp0_iter5_reg <= trunc_ln65_reg_954_pp0_iter4_reg;
        trunc_ln65_reg_954_pp0_iter6_reg <= trunc_ln65_reg_954_pp0_iter5_reg;
        trunc_ln65_reg_954_pp0_iter7_reg <= trunc_ln65_reg_954_pp0_iter6_reg;
        trunc_ln65_reg_954_pp0_iter8_reg <= trunc_ln65_reg_954_pp0_iter7_reg;
        trunc_ln65_reg_954_pp0_iter9_reg <= trunc_ln65_reg_954_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_900_pp0_iter14_reg == 1'd0))) begin
        coeffValue_reg_1048 <= coeffValue_fu_741_p5;
        pixelValue_reg_1053 <= m_axi_gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_904_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_40_reg_925 <= empty_40_fu_465_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln60_5_reg_935_pp0_iter4_reg == 1'd0) & (icmp_ln61_reg_904_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_41_reg_967 <= grp_fu_738_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_fu_401_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln61_reg_904 <= icmp_ln61_fu_412_p2;
        select_ln60_1_reg_915 <= select_ln60_1_fu_417_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_reg_900_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln58_reg_940 <= or_ln58_fu_513_p2;
        p_mid1_reg_944 <= p_mid1_fu_532_p2;
        select_ln58_2_reg_949 <= select_ln58_2_fu_541_p3;
        select_ln60_5_reg_935 <= select_ln60_5_fu_501_p3;
        tmp4_mid1_reg_930 <= grp_fu_420_p_dout0;
        trunc_ln65_reg_954 <= trunc_ln65_fu_557_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_reg_900_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_mid1111_reg_972 <= grp_fu_425_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln60_5_reg_935_pp0_iter4_reg == 1'd1) & (icmp_ln60_reg_900_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_mid162_reg_978 <= grp_fu_589_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_reg_900_pp0_iter16_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln3_reg_1068 <= {{grp_fu_758_p2[51:20]}};
    end
end

always @ (*) begin
    if (((icmp_ln60_reg_900_pp0_iter16_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_fu_401_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln60_reg_900_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter6_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter17_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln60_reg_900_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_1_phi_fu_340_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_1_phi_fu_340_p4 = first_iter_1_reg_335;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_1_ce0 = 1'b1;
    end else begin
        filterCoeffs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_2_ce0 = 1'b1;
    end else begin
        filterCoeffs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_3_ce0 = 1'b1;
    end else begin
        filterCoeffs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_4_ce0 = 1'b1;
    end else begin
        filterCoeffs_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_5_ce0 = 1'b1;
    end else begin
        filterCoeffs_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_6_ce0 = 1'b1;
    end else begin
        filterCoeffs_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_7_ce0 = 1'b1;
    end else begin
        filterCoeffs_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_8_ce0 = 1'b1;
    end else begin
        filterCoeffs_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        filterCoeffs_ce0 = 1'b1;
    end else begin
        filterCoeffs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln58_reg_940_pp0_iter7_reg == 1'd1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln60_reg_900_pp0_iter14_reg == 1'd0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_454_ce = 1'b1;
    end else begin
        grp_fu_454_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_458_ce = 1'b1;
    end else begin
        grp_fu_458_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_577_ce = 1'b1;
    end else begin
        grp_fu_577_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_581_ce = 1'b1;
    end else begin
        grp_fu_581_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_585_ce = 1'b1;
    end else begin
        grp_fu_585_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_589_ce = 1'b1;
    end else begin
        grp_fu_589_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_758_ce = 1'b1;
    end else begin
        grp_fu_758_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln58_reg_940_pp0_iter7_reg == 1'd1))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln60_reg_900_pp0_iter14_reg == 1'd0))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_777_p2 = (trunc_ln3_reg_1068 + acc_fu_116);

assign acc_out = acc_fu_116;

assign add_ln58_1_fu_665_p2 = (zext_ln58_1_fu_661_p1 + input_r);

assign add_ln58_fu_649_p2 = (zext_ln58_fu_645_p1 + zext_ln60_cast_reg_880);

assign add_ln60_1_fu_406_p2 = (indvar_flatten161_fu_136 + 96'd1);

assign add_ln60_fu_395_p0 = iChannel_1_fu_132;

assign add_ln60_fu_395_p2 = ($signed(add_ln60_fu_395_p0) + $signed(32'd1));

assign add_ln61_1_fu_425_p2 = (indvar_flatten70_fu_128 + 64'd1);

assign add_ln61_fu_507_p2 = (select_ln60_fu_477_p3 + 32'd1);

assign add_ln62_fu_561_p2 = (select_ln58_fu_524_p3 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln60_reg_900_pp0_iter14_reg == 1'd0) & (m_axi_gmem0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln60_reg_900_pp0_iter14_reg == 1'd0) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter15 == 1'b1) & (icmp_ln60_reg_900_pp0_iter14_reg == 1'd0) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_io)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state16_pp0_stage0_iter15 = ((icmp_ln60_reg_900_pp0_iter14_reg == 1'd0) & (m_axi_gmem0_RVALID == 1'b0));
end

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((or_ln58_reg_940_pp0_iter7_reg == 1'd1) & (m_axi_gmem0_ARREADY == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_40_fu_465_p2 = (cy_fu_124 + y);

assign empty_42_fu_470_p1 = cy_fu_124[1:0];

assign empty_44_fu_537_p1 = add_ln61_fu_507_p2[1:0];

assign filterCoeffs_1_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_2_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_3_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_4_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_5_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_6_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_7_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_8_address0 = zext_ln58_2_fu_696_p1;

assign filterCoeffs_address0 = zext_ln58_2_fu_696_p1;

assign grp_fu_371_p_ce = grp_fu_454_ce;

assign grp_fu_371_p_din0 = iChannel_reg_890;

assign grp_fu_371_p_din1 = inputWidth;

assign grp_fu_420_p_ce = grp_fu_458_ce;

assign grp_fu_420_p_din0 = add_ln60_reg_895;

assign grp_fu_420_p_din1 = inputWidth;

assign grp_fu_425_p_ce = grp_fu_585_ce;

assign grp_fu_425_p_din0 = tmp4_mid1_reg_930;

assign grp_fu_425_p_din1 = inputHeight;

assign grp_fu_734_p_ce = grp_fu_577_ce;

assign grp_fu_734_p_din0 = tmp4_reg_920;

assign grp_fu_734_p_din1 = inputHeight;

assign grp_fu_738_p_ce = grp_fu_581_ce;

assign grp_fu_738_p_din0 = empty_40_reg_925;

assign grp_fu_738_p_din1 = inputWidth;

assign icmp_ln60_fu_401_p2 = ((indvar_flatten161_fu_136 == mul_ln13_1) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_412_p2 = ((indvar_flatten70_fu_128 == mul_ln13) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_496_p2 = ((cx_fu_120 == convWidth) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = sext_ln58_fu_680_p1;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = convWidth;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign or_ln58_1_fu_519_p2 = (select_ln60_5_fu_501_p3 | icmp_ln61_reg_904_pp0_iter2_reg);

assign or_ln58_fu_513_p2 = (select_ln60_5_fu_501_p3 | or_ln60_fu_484_p2);

assign or_ln60_fu_484_p2 = (icmp_ln61_reg_904_pp0_iter2_reg | ap_phi_mux_first_iter_1_phi_fu_340_p4);

assign p_cast10_fu_596_p1 = empty_41_reg_967;

assign p_cast10_mid1117_cast_fu_352_p1 = p_cast10_mid1117;

assign p_cast10_mid1_fu_629_p1 = p_mid162_reg_978;

assign p_mid1_fu_532_p2 = (add_ln61_fu_507_p2 + y);

assign select_ln58_1_fu_638_p3 = ((select_ln60_5_reg_935_pp0_iter5_reg[0:0] == 1'b1) ? tmp5_mid1_fu_632_p2 : select_ln60_3_fu_622_p3);

assign select_ln58_2_fu_541_p3 = ((select_ln60_5_fu_501_p3[0:0] == 1'b1) ? empty_44_fu_537_p1 : select_ln60_4_fu_489_p3);

assign select_ln58_fu_524_p3 = ((or_ln58_1_fu_519_p2[0:0] == 1'b1) ? 32'd0 : cx_fu_120);

assign select_ln60_1_fu_417_p2 = iChannel_1_fu_132;

assign select_ln60_1_fu_417_p3 = ((icmp_ln61_fu_412_p2[0:0] == 1'b1) ? add_ln60_fu_395_p2 : select_ln60_1_fu_417_p2);

assign select_ln60_2_fu_608_p3 = ((icmp_ln61_reg_904_pp0_iter5_reg[0:0] == 1'b1) ? p_mid1111_reg_972 : empty_reg_961);

assign select_ln60_3_fu_622_p3 = ((icmp_ln61_reg_904_pp0_iter5_reg[0:0] == 1'b1) ? tmp5_mid1119_fu_617_p2 : tmp5_fu_599_p2);

assign select_ln60_4_fu_489_p3 = ((icmp_ln61_reg_904_pp0_iter2_reg[0:0] == 1'b1) ? 2'd0 : empty_42_fu_470_p1);

assign select_ln60_5_fu_501_p3 = ((icmp_ln61_reg_904_pp0_iter2_reg[0:0] == 1'b1) ? icmp_ln44_1 : icmp_ln62_fu_496_p2);

assign select_ln60_fu_477_p3 = ((icmp_ln61_reg_904_pp0_iter2_reg[0:0] == 1'b1) ? 32'd0 : cy_fu_124);

assign select_ln61_1_fu_431_p3 = ((icmp_ln61_fu_412_p2[0:0] == 1'b1) ? 64'd1 : add_ln61_1_fu_425_p2);

assign select_ln61_fu_549_p3 = ((select_ln60_5_fu_501_p3[0:0] == 1'b1) ? add_ln61_fu_507_p2 : select_ln60_fu_477_p3);

assign sext_ln58_fu_680_p1 = $signed(sext_ln62_mid2_v_reg_988);

assign sext_ln62_mid2_v_v_v_v_v_fu_654_p3 = {{add_ln58_reg_983}, {2'd0}};

assign tmp5_fu_599_p2 = (zext_ln61_fu_593_p1 + p_cast10_fu_596_p1);

assign tmp5_mid1119_fu_617_p2 = (zext_ln61_1_fu_605_p1 + p_cast10_mid1117_cast_reg_885);

assign tmp5_mid1_fu_632_p2 = (zext_ln60_1_fu_613_p1 + p_cast10_mid1_fu_629_p1);

assign trunc_ln65_fu_557_p1 = select_ln58_fu_524_p3[1:0];

assign zext_ln58_1_fu_661_p1 = sext_ln62_mid2_v_v_v_v_v_fu_654_p3;

assign zext_ln58_2_fu_696_p1 = select_ln60_1_reg_915_pp0_iter13_reg;

assign zext_ln58_fu_645_p1 = select_ln58_1_fu_638_p3;

assign zext_ln60_1_fu_613_p1 = select_ln60_2_fu_608_p3;

assign zext_ln60_cast_fu_348_p1 = zext_ln60;

assign zext_ln61_1_fu_605_p1 = p_mid1111_reg_972;

assign zext_ln61_fu_593_p1 = empty_reg_961;

always @ (posedge ap_clk) begin
    zext_ln60_cast_reg_880[33:32] <= 2'b00;
    p_cast10_mid1117_cast_reg_885[32] <= 1'b0;
end

endmodule //Conv2D_HW_Conv2D_HW_Pipeline_loop_acc_x
